synapseclient/__main__.py

Updated 'synapse cat' to use sys.stdout to write instead of print, so extra line breaks are not added.
Also changed a couple of variable names ('file' to 'filepath', 'input' to 'inputfile') as 'file' and 'input' are reserved Python built-ins or names.

Fix synapse cat printing extra line breaks

---

synapseclient/activity.py

Minor update to Activity docs to make the list example consistent with others: `activity.used(...)` instead of `used(...)`.

made list example consistent with others

---

synapseclient/__main__.py
synapseclient/client.py
synapseclient/exceptions.py

How do you feel about receiving pull requests?  
This is a bit of a cosmetic change to make the "synapse" command handle authentication in a slightly more interactive way.  (Although I can imagine one could debate how it should work.)
I have an aversion to putting passwords in scripts, so I didn't want to use "syn.login("username", "secret")"
I then read I could cache credentials with the command line client via "synapse login -u username -p secret --remember-me" but I have an aversion to typing passwords as arguments (it means the password is visible in the output of "ps -o args")   In this case, the process is so short lived, it's not a real threat, but I prefer to be prompted for passwords with no echo.
I introduced changes so that if no credentials are cached, it prompts for …

Changes so that username and password are prompted for if not provided.

---

synapseclient/__main__.py
synapseclient/client.py
synapseclient/dict_object.py
synapseclient/entity.py
tests/integration/integration_test_Entity.py
tests/integration/test_command_line_client.py
tests/integration/test_sftp_upload.py
tests/unit/unit_test_Entity.py
tests/unit/unit_tests.py

Partial solution for SYNPY-298 file name override for external files and sftp files and fixes for a couple of unicode issues.

Partial solution for SYNPY-298 fileNameOverride

---

synapseclient/__init__.py
synapseclient/activity.py
synapseclient/annotations.py
synapseclient/cache.py
synapseclient/client.py
synapseclient/evaluation.py
synapseclient/multipart_upload.py
synapseclient/table.py
synapseclient/team.py
tests/unit/unit_test_tables.py

Many outdated links to rest.synapse.org changed to docs.synapse.org/rest

fix rest doc links

---

tests/unit/unit_test_Cache.py

The test was breaking on Windows machines because they used '\\' instead of '/'

fixed test for Windows machines (SYNPY-393)

---

synapseutils/sync.py

`METEDATA` should be `METADATA`

fix spelling mistake in metadata manifest file name

---

synapseclient/client.py
synapseclient/entity.py
tests/integration/integration_test_Entity.py

A Link should always point to the latest version if the version Number isn't set by users.

Link class should not auto set targetVersionNumber

---

synapseclient/table.py
tests/unit/unit_test_tables.py

Reverts Sage-Bionetworks/synapsePythonClient#497
The backend will be permissive with json Row values. So we should go back to using ints, floats, etc... in the `values` list. This also makes the using the retrieved data more intuitive for users.

Revert "Row and PartialRow now always cast values to string (SYNPY-615)" (SYNPY-616)

---

tests/integration/test_tables.py

to avoid dict object to be out of order in Python 2

SYNPY-799 Fix dict out of order in Python 2

---

synapseutils/copy.py
tests/unit/unit_test_synapseutils_copy.py

PLFM-5305, SYNPY-1018
This should be a patch to master so that users can't copy files with access restrictions.

SYNPY-999 Don't copy entities with access restrictions

---

synapseclient/synapsePythonClient

When trying to include this package as a dependency by using a `requirements.txt` like this:
```
git+https://www.github.com/Sage-Bionetworks/synapsePythonClient.git@v1.9.4-develop
git+https://www.github.com/bsmn/ndasynapse.git@v0.4.3
```
with a version number of `v1.9.4-develop`, I get:
```
ERROR: ndasynapse 0.4.3 has requirement synapseclient>=1.7.2, but you'll have synapseclient 1.9.4-develop which is incompatible.
```
This indicates that the version number is not comparable and it bumps me back down to the latest release on PyPi (`v1.9.3`). The standard ([PEP-440](https://www.python.org/dev/peps/pep-0440/#developmental-releases)) indicates the format should be `v1.9.4.devN` where `N` is a non-negative integer.

Change internal version number to be comparable.

---

synapseutils/copy.py
tests/unit/unit_test_synapseutils_copy.py

Currently the permissions of entities aren't checked, so copy function attempts to copy entities with VIEW permissions and fails.

SYNPY-881 Don't copy entities that don't have DOWNLOAD permission

---

tests/unit/unit_test_synapseutils_copy.py

This test failed, because `syn.getPermissions` was added.

Fix copy test: Add mocking of syn.getPermission

---

synapseclient/client.py
tests/integration/integration_test_Entity.py
tests/unit/unit_test_client.py

This functionality includes 4 convenience functions that wrap rest calls
* get team open invitations (GET)
* get membership status of a user (GET)
* delete membership invitation (DELETE)
* membership invitation (POST)
It also has a helper function that allows users to invite a Synapse user or an email to a Synapse team.  If the user is already part of the team, it will not send an invitation.  If an open invitation exists, the user will not be sent an invitation unless `force=True`

SYNPY-851 invite user/email to team

---

synapseclient/client.py

Print out reason for why an invitation was not sent, but return `None`.

SYNPY-851 - Print out invitation not sent reason

---

docs/news.rst
synapseclient/.synapseConfig
synapseclient/__main__.py
synapseclient/client.py
synapseclient/core/multithread_download/download_threads.py
synapseclient/core/upload/multipart_upload.py
synapseclient/core/utils.py
tests/integration/synapseclient/core/upload/test_multipart_upload.py
tests/unit/synapseclient/core/unit_test_download.py
tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py
tests/unit/synapseclient/unit_test_client.py

1. Extends the threading configurability to allow you to specify a value for S3 downloads as well as uploads since it seems nicely symmetrical that way.
2. Adds a [transfer] section to the synapseConfig with a maxThreads option for specifying the setting so you don't have to always specify it on each call. 
3. Makes the public facing API param for maxThreads mixed case since that matches the existing convention on those calls. Internal function params may still be snake_cased per PEP8.
4. Adds some doc for this to the release notes.

maxThreads configurable

---

synapseclient/annotations.py
synapseclient/client.py
tests/integration/synapseclient/test_evaluations.py
tests/unit/synapseclient/unit_test_annotations.py
tests/unit/synapseclient/unit_test_client.py

https://sagebionetworks.jira.com/browse/SYNPY-1056
syn.getSubmission pre fetches the associated entity, and in doing so passes along annotations returned in its entityBundleJSON from the Evaluations api which are old style (stringAnnotations, dateAnnotations, etc.). With recent changes getWithEntityBundle expects new style annotations as used with Entity Bundle Services V2.
This attempts to translate between the two for the purposes of making the getWithEntityBundle call.

SYNPY-1056 - expectation new style annotations breaking getSubmission call

---

synapseclient/activity.py
synapseclient/annotations.py
synapseclient/client.py
synapseclient/core/cache.py
synapseclient/core/models/dict_object.py
synapseclient/core/utils.py
synapseclient/entity.py
synapseclient/table.py

My understanding is the `collections.namedtuple()` and `collections.OrderedDict()` will be obsolete as well in Python 3.10, but there is still some time for that.

SYNPY-1059: Change collections to collections.abc where appropriate

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

https://sagebionetworks.jira.com/browse/SYNPY-1036
https://github.com/Sage-Bionetworks/synapsePythonClient/pull/723 prevented a 403 that occurred while attempting to retrieve the file handle during a store, but another 403 is raised when "creating" the entity later in the store operation if the user is different from the original file handle creator.
Currently we seem to handle every store that doesn't include the entity id as a create (POST /entity) only switching to handling it as an update (PUT /entity/[id]) after the back end returns a 409 conflict error for the create. This mostly works when the user invoking the store is the creator of the file handle, but returns an uncaught 403 for other users.
This change is so that if the the bundle fetch earlier in the store operation returns …

SYNPY-1036 Handle id-less entity updates without a failed create

---

synapseclient/client.py
synapseclient/core/sts_transfer.py
tests/unit/synapseclient/core/unit_test_sts_transfer.py

With https://github.com/Sage-Bionetworks/Synapse-Repository-Services/pull/4067 the Synapse service will return the bucket info along with the STS token. The client can make use of that to avoid an extra call it's currently using to retrieve this info from the upload destination.
A fall back to look at the upload destination is left in for now so that the client can still return this data if it is not running against services deployed with the above.

PLFM-6226 - include bucket info from STS call

---

setup.cfg

https://github.com/Sage-Bionetworks/synapsePythonClient/pull/751 introduced flake8 as its linter and switched pep8speaks to use it as well. It used the flake8 per-file-ignores option to ignore F821 (undefined name) in tests only to how e.g. syn and project are set as module variables in tests, but pep8speaks [doesn't support](https://github.com/OrkoHunter/pep8speaks/pull/151) that option, so it would flag these as issues (but only when part of a diff since that's how we configure pep8speaks). This just extends the ignore to all files, not just tests, for pep8speaks compatibility.

flake8 F821 ignore

---

setup.py

This is to address [SYNPY-1076](https://sagebionetworks.jira.com/browse/SYNPY-1076) which results from a stale pandas dependency breaking when compiled against the latest released version of numpy.
But rather than just upgrade the pinned version this unpins specific package version dependencies instead and allows the installed version to float above a minimum.
My thoughts roughly mirror [these](https://stackoverflow.com/a/44938662). In a controlled deployment environment where all dependencies (including downstream dependencies) can be frozen by an environment manager such as pipenv, then it makes sense to pin all specific versions. But synapseclient is a library that is installed and used in other applications and environments and typically installed through a simple pip install. We …

SYNPY-1076 unpin specific dependency versions

---

synapseclient/annotations.py
synapseclient/client.py
tests/unit/synapseclient/unit_test_annotations.py

https://sagebionetworks.jira.com/browse/SYNPY-1075
In stack 316 archived entityBundleJSON on a Submission is saved/returned using v2 annotations. This allows the client to handle either form, as either form might be returned depending on when the submission was made and the entity JSON was serialized.

SYNPY-1075 handle Submission entityBundleJSON w/ v2 annotations

---

synapseclient/core/utils.py
synapseutils/sync.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

syncFromSynapse when synced to an external location outside the cache generates manifest file(s) in the synced folder structure. For a deep folder structure there are performance issues related to interaction with the recursion and the manifest generation that are more completely described here:
https://sagebionetworks.jira.com/browse/SYNPY-1078
This speeds things up by changing the following:
1. A manifest file that is written to each subdirectory now only includes the files that are rooted in that subdirectory, rather than all files synced so far. The previous behavior of writing those files that happen to have been synced so far doesn't make much sense and seems to be a byproduct of the recursive implementation of the function rather than intentional behavior. It's not clear to me that …

SYNPY-1078 syncFromSynapse manifest performance

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

`urlparse.urlretrieve` doesn't exist anymore.

SYNPY-1082: urlretrieve Use urllib_request

---

synapseclient/table.py

https://sagebionetworks.jira.com/browse/SYNPY-1080
Tables/Views aren't versionable (but are snapshottable).
Extending Versionable results in an update to a table being a versioned put, e.g.
PUT /entity/<sub_view_id>/version
But the backend is just discarding the version per https://sagebionetworks.jira.com/browse/PLFM-6362

SYNPY-1080 Remove Versionable from SchemaBase

---

synapseclient/__main__.py
synapseclient/client.py
synapseclient/core/cumulative_transfer_progress.py
synapseclient/core/multithread_download/__init__.py
synapseclient/core/multithread_download/download_threads.py
synapseclient/core/remote_file_storage_wrappers.py
synapseutils/sync.py
tests/integration/synapseclient/core/test_download.py
tests/unit/synapseclient/core/multithread_download/unit_test_download_threads.py
tests/unit/synapseclient/core/unit_test_cumulative_transfer_progress.py
tests/unit/synapseclient/core/unit_test_download.py
tests/unit/synapseclient/unit_test_client.py
tests/unit/synapseclient/unit_test_commandline.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

https://sagebionetworks.jira.com/browse/SYNPY-1074
Improves performance of syncFromSynapse (synapse get -r) by allowing multiple files from the sync to be dowloaded in parallel. The current implementation downloads files serially (if the existing client is configured in multiThreaded mode each individual S3 file is downloaded in parallel chunks, but the files themselves are still downloaded serially). Some performance stats are included in the linked bug.
In order to achieve this:
1. synapseclient.sync.syncFromSynapse is refactored to use a thread pool Executor service The folder hierarchy is walked in the main entrant thread but the individual files are submitted for asynchronous download in the thread pool. This also necessitates reimplementing syncFromSynapse in an iterative walk …

SYNPY-1074 parallelize syncFromSynapse file downloads

---

synapseclient/client.py
tests/integration/synapseclient/test_evaluations.py
tests/unit/synapseclient/core/unit_test_download.py
tests/unit/synapseclient/unit_test_client.py

https://sagebionetworks.jira.com/browse/SYNPY-1084
Per SYNPY-1084 we always enforce that calls made to Synapse are from a logged in client, even for endpoints that don't require auth. This removes the client preemptively raising a SynapseAuthenticationError with a logged out client and instead allows the call to go through. If the call returns a 401 or 403 status code then the client will then raise a SynapseAuthenticationError chained from the error raised as a result of the call.
Also unifies the implementation of the various Synapse#rest methods which were largely duplicative so that they could be more easily tested.

SYNPY-1084 allow anonymous calls

---

docs/CommandLineClient.rst
docs/conf.py
setup.py
synapseclient/__main__.py

The current command line client docs don't describe any of the arguments to any of the subcommands. This uses [sphinx-argparse](https://sphinx-argparse.readthedocs.io/en/stable/) to generate a more complete documentation leveraging the existing argparse meta data.
Old version:
https://python-docs.synapse.org/build/html/CommandLineClient.html
New version
https://jkiang13.github.io/synapsePythonClient/build/html/CommandLineClient.html

DOCS-4 improve command line client docs

---

synapseclient/__init__.py

The instructions say to use pip, which can commonly point to a Python 2 installation on systems when both Python 2 and 3 are installed and when not using a virtual environment. In most cases where Python 3 is on the path, pip3 will be on the path even in cases where the plain pip command also points to Python 3 (for example in a virtual env).

SYNPY-1087 update installation instructions

---

synapseclient/__main__.py
synapseclient/core/utils.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/unit_test_commandline.py

https://sagebionetworks.jira.com/browse/SYNPY-1090
Allows an api key to be used where the password is in the command line client. It is used in place of a password instead of as a separate command line argument in order to simplify things for the user, in particular when inputting the password from the console input prompt  (don't want them to have to specify which they are using or enter an empty password followed by an api key for example).

SYNPY-1090 Allow use of api key with command line client

---

synapseclient/core/cumulative_transfer_progress.py
synapseclient/core/pool_provider.py
synapseclient/core/upload/multipart_upload.py
synapseclient/core/upload/upload_functions.py
synapseutils/sync.py
tests/integration/synapseutils/test_synapseutils_sync.py
tests/unit/synapseclient/core/unit_test_pool_provider.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

[SYNPY-1073](https://sagebionetworks.jira.com/browse/SYNPY-1073)
Some performance numbers for this change are included in the JIRA issue.
Parallelizes syncToSynapse similar to how syncFromSynapse was parellelized with [SYNPY-1074](https://sagebionetworks.jira.com/browse/SYNPY-1073). Individual Synapse store calls are run in parallel using an Executor shared across all uploads and by the part uploads of the files themselves.
Files specified using provenance of other files in the manifest must have their uploads ordered since we need to be able to include the Synapse id of the uploaded file as provenance of the depending files.

SYNPY-1073 Parellelize syncToSynapse uploads

---

setup.py

Current URL was deprecated and is no longer functioning.

SYNPY-1096 - Update setup.py synapse url

---

.github/workflows/build.yml

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

replace GH actions set-env

---

synapseclient/client.py
synapseclient/core/utils.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/unit_test_client.py

https://sagebionetworks.jira.com/browse/SYNPY-1097
File handle downloads via the client retry the specified number of times (currently defaults to 5) on any exception.
Some exceptions do not represent recoverable scenarios and shouldn't be retried, two that I've observed are MD5 mismatches and out of disk space errors.
The out of disk space errors in particular cause odd behavior in the context of a parallel syncFromSynapse since a file can fail, delete itself, which frees up space for another thread to attempt to continue downloading etc and the threads fight until all have exhausted their retry attempts.
This PR also changes the "human readable" output on an uncaught exception in the command line client to include chained exceptions if the uncaught exception has cause(s). This should …

SYNPY-1097 handle out of disk space errors during downloads better

---

tests/integration/synapseutils/test_synapseutils_copy.py

Integration test used a fixed project name that could cause issues if multiple integration tests were running concurrently. This showed more obviously under GitHub Actions testing since the whole 3x3 test matrix is run concurrently, whereas before the tests happened to be staggered a bit more due to being split across Travis and AppVeyor and since the Travis Mac tests took a lot of time to boostrap brew dependencies.
e.g.
```
>           raise SynapseHTTPError(message, response=response)
E           synapseclient.core.exceptions.SynapseHTTPError: 412 Client Error: 
E           Object: syn11174160 was updated since you last fetched it, retrieve it again and re-apply the update
/Users/runner/work/synapsePythonClient/synapsePythonClient/synapseclient/core/exceptions.py:160: SynapseHTTPError …
```

Name integration test project for TestCopyFileHandles uniquely per run

---

synapseutils/sync.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

syncToSynapse will parse and set an empty string as an annotation value from a manifest TSV file if an upload row doesn't contain a value for that annotation. We'd prefer that on a manifest sync it set no annotation for that key if there is no value rather than an empty string.
https://sagebionetworks.jira.com/browse/SYNPY-1102

SYNPY-1102 - filter out empty string annotations on syncToSynapse

---

synapseclient/core/constants/concrete_types.py
synapseclient/core/upload/multipart_upload.py
tests/integration/synapseclient/core/upload/test_multipart_upload.py
tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py

Part 1 of 2 PRs for [SYNPY-1103](https://sagebionetworks.jira.com/browse/SYNPY-1103)
This PR refactors the existing multipart upload code to also support [multipart copies](https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/file/MultipartUploadCopyRequest.html).

SYNPY-1103 multipart copy support

---

setup.py

I get the following warning when installing `synapseclient` using Poetry. I think the one-line change in this PR addresses the issue. 
```
PackageInfo: Invalid constraint (sphinx-argparse<.3,>=0.2 ; extra == "docs") found in synapseclient-2.2.2 dependencies, skipping
```

Fix invalid version constraint on sphinx-argparse

---

synapseclient/__main__.py
tests/unit/synapseclient/unit_test_commandline.py

Fix the odd behavior when console login on Windows.
Check the terminal is tty or not, if False, throw the exception for the user
If the ommand line user typed in with no function argument, print out the help instruction. 
Create three unit tests for commandline.py
- command_auto_login
- no_command_print_help
- login_with_prompt_no_tty

SYNPY-1110-fix the console log on Windows

---

synapseclient/core/cache.py
tests/unit/synapseclient/core/unit_test_Cache.py

Currently a .cacheMap file in the synapseCache that is not parseable as JSON will raise an error whenever a download is attempted of the associated file. For robustness this treats an unparseable cacheMap entry as if it does not exist, a new cacheMap entry will be written on a download rather than an error raised.
https://sagebionetworks.jira.com/browse/SYNPY-1109

SYNPY-1109 handle cacheMap files not parseable as JSON

---

.github/workflows/build.yml
setup.py

Adds Python 3.9 as a classifier and to the build matrix.
Currently there are no wheels available for numpy or pandas for 3.9 so it makes sense to wait for those to become available to include the support classifier in a synapseclient since installs would then have to compile these dependencies which is slow and error prone.
This also changes it so that we only run integration tests and the lowest and highest supported python versions (3.6 and 3.9 as of this PR) rather than all supported versions, otherwise running 3x4 integration test runs is overkill and can cause slower builds due to build runner limits and lead to some spurious build failures (especially our SFTP tests which can hit connection errors communicating with the EC2 host used for tests if too many tests hit it at once).

SYNPY-1104 Python 3.9

---

synapseutils/migrate_functions.py
tests/integration/synapseutils/test_synapseutils_migrate.py
tests/unit/synapseutils/unit_test_synapseutils_migrate.py

https://sagebionetworks.jira.com/browse/SYNPY-1112
The storage location migration utility will attempt to copy a new file handle for every entity that it copies. If two entities/versions share the same file handle and an attempt is made to copy them concurrently, it produces a DuplicateKeyException in the backend. However the utility should only be copying each file handle once and re-using the newly copied handle for each entity/version that shares the same source file handle id.

SYNPY-1112 re-use matching file handles during a storage migration

---

setup.py

Conditionally specifies a version of cryptography < 3.4 to mitigate issues arising from its new dependence on a Rust compiler when compiling from source.

SYNPY-1114 mitigate Linux cryptography version Rust compiler dependency

---

setup.py
synapseclient/__main__.py
synapseutils/migrate_functions.py
tests/unit/synapseclient/unit_test_commandline.py
tests/unit/synapseutils/unit_test_synapseutils_migrate.py

Use the part size recommended in https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/file/MultipartUploadCopyRequest.html rather than using the same default part size as an upload. In particular ensure that we don't exceed the maximum 10000 part limit (this was being enforced for uploads but not for copies).
Also fixes an issue where if you declined to proceed with a migration it would produce an exception rather than exiting cleanly.

SYNPY-1103 multipart copy part size

---

.github/workflows/build.yml
tests/integration/synapseclient/core/upload/Dockerfile_sftp
tests/integration/synapseclient/core/upload/test_sftp_upload.py

This replaces the use of a fixed EC2 instance as a storage location for Python integration tests with a container that is created during the GH Actions CI run.
This is simpler and has no external dependency. The one downside is that Windows and Mac integration tests cannot use it because GH Actions doesn't support containers for those platforms, and you can't share a container across matrix jobs, so specifically veriyfing SFTP integration on those platforms requires manually setting an SFTP_HOST and running the tests (can still use the Docker just not within GH Actions).
The SFTP integration tests look for an "SFTP_HOST" environment variable and will test against those, using matching credentials found in the synapseConfig.

SYNPY-1117 containerized sftp integration tests

---

synapseclient/__main__.py
synapseclient/client.py
synapseclient/core/multithread_download/download_threads.py
synapseclient/core/remote_file_storage_wrappers.py
synapseclient/core/upload/multipart_upload.py
tests/unit/synapseclient/core/multithread_download/unit_test_download_threads.py
tests/unit/synapseclient/core/unit_test_remote_storage_file_wrappers.py
tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py
tests/unit/synapseclient/unit_test_client.py
tests/unit/synapseclient/unit_test_commandline.py

change
- add silent mode option for command line and pass in as an argument to create Synapse instance
-  If silent is true, the logger will change to silent user and won't print out the transfer progress on terminal
- add unit test for commandline.py/ client.py/ remote_storage_file_wrappers.py

Synpy 929(834) silent parameter functions

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

If a user hasn't taken the quiz at all the backend returns a 404. We should handle that and return False from is_certified.

SYNPY-1111 handle no quiz result 404

---

synapseutils/migrate_functions.py
tests/unit/synapseutils/unit_test_synapseutils_migrate.py

Fixes an issue where file handles shared by multiple files could end up getting migrated twice concurrently, producing an error on the second attempt.

SYNPY-1118 better migration handling for shared file handles

---

docs/S3Storage.rst
synapseclient/__main__.py
synapseutils/migrate_functions.py
tests/unit/synapseclient/unit_test_commandline.py
tests/unit/synapseutils/unit_test_synapseutils_migrate.py

Currently *synapseutils.index_files_for_migration* will index all files not already in the destination storage location. @Aryllen requested an option to limit migration to files in specific storage locations since it may be the case that she will have a Project/Folder with files in multiple storage locations and only wants those in the specific storage locations migrated.

SYNPY-1119 add option to limit storage location migration to specific source storage locations

---

synapseclient/__main__.py
synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py
tests/unit/synapseclient/unit_test_commandline.py

Change
- If the entity id is project or folder and downloadFile is True, the synapse get method with restriction should not raise the error msg but only warning msg
- modified the _check_entity_restrictions private function and pass in the whole bundle to check the entity type
- add unit tests and fix the issue that changed from the modification in client.py

Synpy 198 error entity undownloadable

---

tests/unit/synapseclient/unit_test_commandline.py

Fixes test expectation issue arising from the merge of PRs 822 and 828
https://github.com/Sage-Bionetworks/synapsePythonClient/pull/822
https://github.com/Sage-Bionetworks/synapsePythonClient/pull/828

Fix test merge conflict

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

Change
- add checking logic to make properties['versionComment'] with the value or None
- add unit test to check update correctly

Synpy 1033 store issue for blank version comment

---

synapseclient/core/remote_file_storage_wrappers.py
tests/integration/synapseclient/core/test_external_storage.py
tests/unit/synapseclient/core/unit_test_remote_storage_file_wrappers.py

https://sagebionetworks.jira.com/browse/SYNPY-1138

SYNPY-1138 apply bucket-owner-full-control ACL on Synapse boto uploads

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

https://sagebionetworks.jira.com/browse/SYNPY-1115
Table objects have a defined **_synapse_store** method which short circuits the normal entity storage during a Synapse#store. This also prevents any passed provenance from being applied to a table during a table store.
This factors out the provenance handling into a private helper that is also used to apply provenance after an object is stored via a _synape_store call.

SYNPY-1115 table provenance not applied on a store

---

synapseclient/__main__.py
tests/unit/synapseclient/unit_test_commandline.py

Change
- fix the issue for the confused msg when enter get command without synapse ID
`TypeError: 'NoneType' object is not subscriptable`
- add unit test for the value error case

SYNPY-1141-get_command_line_nargs_error

---

synapseclient/client.py
tests/integration/synapseclient/integration_test_Entity.py
tests/integration/synapseutils/test_synapseutils_sync.py
tests/unit/synapseclient/core/unit_test_download.py

Change
- fix the issue for the ticket that is "FileEntity 'path' property has the wrong separator for Windows"
https://sagebionetworks.jira.com/browse/SYNPY-959
- fix the unit tests and integration tests since this change

Synpy 959 file entity path separator in windows

---

synapseclient/evaluation.py
tests/integration/synapseclient/test_evaluations.py
tests/unit/synapseclient/unit_test_Evaluation.py

Per https://sagebionetworks.jira.com/browse/PLFM-2631 the status field is no longer used as part of the Evaluation and is not a field of [Evaluation](https://rest-docs.synapse.org/rest/org/sagebionetworks/evaluation/model/Evaluation.html). The client still accepts a status kwarg and auto populates one of one is not passed. This field is being ignored in the backend so it can be removed.

SYNPY-1024 remove Evaluation status

---

tests/unit/synapseclient/unit_test_client.py

Change
- add a unit test to verify the issue is fixed and preserve the exception msg

Synpy 872 download file handle loses stack trace error

---

synapseclient/__main__.py

Results in the following argparse usage string:
```
usage: synapse query [-h] [string [string ...]]
positional arguments:
string      A query string. Note that when using the command line query strings must be passed intact as a single string. In most shells this can mean wrapping the query in quotes as
appropriate and escaping any quotes that may appear within the query string itself. Example:: synapse query "select \"column has spaces\" from syn123" See
https://docs.synapse.org/rest/org/sagebionetworks/repo/web/controller/TableExamples.html' for more information
optional arguments:
-h, --help  show this help message and exit
```
And the html representation on our docs site would be as follows:
https://jkiang13.github.io/synapsePythonClient/build/html/CommandLineClient.html#query

SYNPY-1143 synapse query CLI command needs a quoted query string

---

tests/integration/synapseclient/core/test_caching.py

Fix a race condition in test_caching that caused unpredictable errors.
Explanation in JIRA issue: https://sagebionetworks.jira.com/browse/SYNPY-1158

SYNPY-1158 test_caching race condition

---

synapseclient/core/credentials/credential_provider.py
tests/unit/synapseclient/core/credentials/unit_test_cred_provider.py

username/email is not required when logging in via an authToken but if one is provided it is compared to the token profile's username to avoid ambiguity.  We should additionally allow it to match a profile email address (especially since the username kwarg is historically named "email").

SYNPY-1159 allow passing an email as a username when logging in with authToken

---

synapseclient/__main__.py

This PR removes all single hyphen arguments, that are also not single letter. The one exception is the removal of `-type` entirely from line 588 for it being redundant.
The attribute `.type` in the `add_parser` subparser is already defined on line 576 in the mutually exclusive argument group ( `parent_id_group` ).

[SYNPY-737] Remove non-standard single hyphen long arguments

---

synapseclient/table.py
tests/integration/synapseclient/test_tables.py

When storing tables, it's not always going to be a Schemas object that gets passed in.  A synapse id is also possible.

[SYNPY-1197] Schema isn't always a entity

---

synapseclient/__init__.py
synapseclient/table.py
tests/integration/synapseclient/test_tables.py
tests/unit/synapseclient/unit_test_tables.py

Supports materialized views as described here: https://sagebionetworks.jira.com/wiki/spaces/PLFM/pages/2514321554/Synapse+Joins
Heres how you test this branch:
1. Create a new Python virtualenv
2. Install this specific branch
```
pip install pandas
pip install https://github.com/thomasyu888/synapsePythonClient/archive/refs/heads/synpy-1209-materializedviews.zip
```
3. Run code with replacements of synapse ids and join
```
from synapseclient.table import MaterializedViewSchema
syn = synapseclient.Synapse()
syn = synapseclient.login()
temp = MaterializedViewSchema(
name="test-material-view",
parent="syn34234",
definingSQL="SELECT * FROM syn111 F JOIN syn2222 P on (F.PATIENT_ID = P.PATIENT_ID)"
)
ent = syn.store(temp)
temp = syn.tableQuery(f"select * from {ent.id}") …
```

[SYNPY-1209] Support materialized views

---

synapseclient/entity.py

Due to there being a property named `items` in the Dataset schema, calling `self.properties.items()` results in a TypeError in the `__repr__()` method.
This PR will address #913 by utilizing the good ol' fashion way of getting a dictionary value by using its key instead.
**Before fix:**
```python
>>> dataset = syn.get("syn29430164")
>>> repr(dataset)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/vchung/Desktop/synapsePythonClient/synapseclient/entity.py", line 434, in __repr__
self.properties.items(),
TypeError: 'list' object is not callable
>>> 
```
**After fix:**
```python
>>> repr(dataset)
"Entity(, modifiedBy='3393723', versionNumber=1, isLatestVersion=True, items=[{'entityId': 'syn20685093', 'versionNumber': 1}], parentId='syn20682803', …
```

[SYNPY-1219] update Entity __init__ to be compatible with Dataset

---

synapseclient/entity.py
synapseclient/table.py

This will make it so all properties are consistent with styling; currently, `dataset_items` is using snake case while all other properties are using camel case.

[SYNPY-1207] Update property name

---

synapseclient/table.py

* Add default annotations
* Add all annotations
Here's how you test this branch:
1. Go on Synapse and add to your download list
2. Create a new Python virtualenv
3. Install this specific branch
```
pip install pandas
pip install https://github.com/thomasyu888/synapsePythonClient/archive/refs/heads/SYNPY-1226-use-viewbase-for-datasets.zip
```
4. Test feature. (You will want to replace the synapse ids)
```
syn = synapseclient.login()
dataset_items = [
{"entityId": "syn2334", "versionNumber": 1}
]
dataset = synapseclient.Dataset(
name="My test dataset", parent="syn33333",
dataset_items=dataset_items
)
syn.store(dataset)
```
5. confirm your dataset online has all expected annotations

[SYNPY-1226] use viewbase for datasets

---

synapseutils/sync.py

This is to elaborate on issue #899 with a concrete PoC with desired functionality. I don't know if the approach is the desired / most efficient one!

Add onlyMatching argument to syncFromSynapse to filter downloads

---

synapseclient/client.py

Alternatively, an error can be thrown instead to let users know they have to specify resultsAs="rowset" to leverage the `isConsistent` parameter
This parameter is actually ignored in the backend.

[SYNPY-226] Remove isInconsistent kwarg when results are returned as csv

---

setup.py
synapseclient/activity.py
synapseclient/client.py
synapseclient/core/utils.py
synapseutils/sync.py
tests/integration/conftest.py

Fixes #947 , so that the utils function name is more descriptive.
The expected pattern has also been updated to be a little more stringent, that is, the synID should start with `syn` and end with a digit.

update name of utils function: `is_synapse_id`

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

Fixes #948
Aside from the unit tests, I also did tests with real Synapse entities:
```python
>>> # Not real IDs
>>> syn.is_synapse_id("test")
False
>>> syn.is_synapse_id("123")
False
>>> syn.is_synapse_id("syn123")
False
>>> # Real IDs
>>> syn.is_synapse_id("syn36025126")
True
>>> # Also works when user is logged out or lacks access
>>> syn.logout()
>>> syn.is_synapse_id("syn36025126")
True
>>> # Warning will be given if synID is not a string
>>> syn.is_synapse_id([123])
[WARNING] synID must be a string
False
```
Note: this should probably be merged after #949, since that PR contains fixes to the workflow.

SYNPY-1248: add `is_synapse_id` function to the client

---

.github/workflows/build.yml

* upgrade deprecated ubuntu github action runner
* Update almost deprecated `set-output` command
* Upgrade action versions used

[SYNPY-1257] Hotfix - upgrade github actions

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_tables.py

Prior to this change, syncFromSynapse seems to always throw a warning with the default parameters.  This will silence that

[SYNPY-570] Make sure warning doesn't appear ifcollision is overwrite.local

---

setup.py
synapseclient/__init__.py
synapseclient/core/version_check.py
tests/integration/synapseutils/test_synapseutils_copy.py

Replace `pkg_resources` call with `importlib.resources`

`pkg_resources` is a deprecated API - replace with importlib.resources

---

synapseclient/client.py
tests/integration/synapseclient/integration_test.py
tests/unit/synapseclient/unit_test_client.py

**Problem:**
During the previous logic in `getPermissions` only if the ACL returned for the entity matched the ID of the user exactly would permissions be returned. This means that any permissions given through the Teams the user is a part of were not returned.
**Solution**
Modified the logic in `getPermissions` to retrieve a list of Teams the user is a part of. Then - When we are looking over the ACL for the entity return a unique list of permissions granted on the entity for 1) The user, 2) All teams the user is a member of.
**Testing**
1. Unit tests:
- synapsePythonClient/tests/unit/synapseclient/unit_test_client.py::TestPermissionsOnProject::test_get_permissions_with_defined_set_for_access PASSED
- synapsePythonClient/tests/unit/synapseclient/unit_test_client.py::TestPermissionsOnProje …

[SYNPY-49] Aggregate acl based on groups

---

synapseclient/client.py
synapseclient/core/utils.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/unit_test_client.py

* Deprecated `memoize` and replaced it with `lru_cache` for Python 3.8 and above https://docs.python.org/3.8/library/functools.html#functools.lru_cache
* Since we are no longer using `memoize`, I also removed `refresh` parameter in login method
* Updated test
* Note: to address the pre-commit error below, I also updated `hashlib.md5()` by using `usedforsecurity=False` parameter:
```
[main]  INFO    running on Python 3.11.3
Run started:2023-06-27 22:10:20.620752
Test results:
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
Severity: High   Confidence: High
CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
More Info: https://bandit.readthedocs.io/en/0.0.0/plugins/b324_hashlib.html
Location: synapseclient/client.py:2588:30
2587 …
```

[SYNPY-967] deprecated memoize and added @lru_cache

---

synapseclient/client.py
synapseclient/core/utils.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/unit_test_client.py

This reverts commit 432feca4205f913a9692436b4a0897aeabfc0833, reversing changes made to 0d1721fffd74231e477d8c15dad6a98e0988df53.

Revert "Merge branch 'linglp/synpy-967-linglp' to develop"

---

docs/build/html/articles/cli.html
synapseclient/__main__.py

This PR replaces a broken URL with the correct one pointing to the documentation of `synapseutils.sync.syncToSynapse` in `__main__.py.

[SYNPY-1283] Replace Broken Link URL

---

synapseclient/__main__.py

This PR follows-on from #989 to add a trailing space to the URL that I replaced earlier.

[SYNPY-1283] Adds Missing Trailing Space (Broken Link Fix)

---

docs/getting_started/credentials.rst

Adding information about the `synapse config` command.
This is what the new section looks like:
I also added a link to the CLI `synapse config` in the more information section

[SYNPY-1295] Adding to the credentials.rst doc

---

synapseclient/client.py
tests/integration/synapseclient/integration_test.py

**Problem:**
When an entity is created the `set_annotations` method is always being called even if the entity is being created without any annotations.
A side-effect of this is that it is causing some Integration test instability - It also saves an extra HTTP call when creating a new entity w/o annotations.
1. https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/6501857782/job/17659897335#step:8:344
2. https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/6511652889/job/17687757507#step:8:343
**Solution:**
Checking to see if we are creating the entity in the first place only call `set_annotations` if there are annotations to be set.
**Testing:**
I added 2 Integration tests around this logic.

[SYNPY-1298] Update annotation logic

---

synapseclient/client.py
tests/integration/synapseclient/integration_test_Entity.py
tests/unit/synapseclient/core/unit_test_download.py

Problem:
When items in the cache on local machine had the same name for a file it would some-times assume it was the intended file to download and would not download the correct file from Synapse. Instead it would copy the incorrect file (With the correct name) to the requested location.
Solution:
I am doing a MD5 check of the cached item and the item from the server to verify they match
Testing:
1. I tested this is the script located in the comments on: https://sagebionetworks.jira.com/browse/SYNPY-1316
2. I also verified that with and without the changes that the introduced integration test passes/fails

[SYNPY-1316] Fix for cache item names matching

---

tests/integration/synapseclient/integration_test_Entity.py

Problem:
Windows doesn't overwrite in an os.rename
`FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'c:/users/runner~1/appdata/local/temp/tmplrhaqh7f.dat' -> 'c:/users/runner~1/appdata/local/temp/tmpj45y4tsc.dat'`
Solution:
Delete destination file before rename

Fix for int test on windows for file rename

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.pre-commit-config.yaml
docs/requirements.txt
synapseclient/client.py

**Problem:**
We were only running the black linter during the GH action - which does not enforce everything the `pre-commit` check did.
**Solution:**
I set up  `pre-commit` job that runs this action: https://github.com/pre-commit/action
**Testing:**
1. Failure in pre-commit: https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/6710081386/job/18234512611
2. Success in pre-commit: https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/6710112140/job/18234608303

[SYNPY-1274] pre commit in gh action

---

.github/workflows/build.yml
Pipfile.lock
setup.cfg

Problem:
Installing the python client forces a downgrade of the cryptography package to <3.4 - It is not optional as the comments of the file are implying
Solution:
Remove the 3.4 cryptography package as a required install. Instead let it be installed by anything that requires it.

[SYNPY-1316] Make cryptography an optional install

---

synapseclient/client.py
synapseclient/core/cache.py
tests/unit/synapseclient/core/unit_test_Cache.py
tests/unit/synapseclient/core/unit_test_download.py

Problem:
In the `.cacheMap` file there is a key-value pair of path to file for a particular file handle ID and it's associated modified time, for example:
`{"/home/bfauble/synapseTestFiles/bryansTestProject/temp/file_1.txt": "2023-11-03T21:46:48.000Z"}`
In cases where we are downloading files into the same directory and a file with the same name is matching the current cache mechanism can incorrectly assume the file is already present in the directory and not attempt to download a new copy with `ifcollision='overwrite.local`
Solution:
- When we are adding new items to the cache store the file MD5 at the time of caching too. When we are checking for a cache hit verify if the local file has a different modification time and (if present) that the md5's match. If neither pass treat this as a …

[SYNPY-1316] Updating to caching logic to take in MD5 key

---

synapseclient/core/utils.py

**Problem:**
https://sagebionetworks.jira.com/browse/SYNPY-1319
One or more parts fails to upload
**Solution:**
To try to limit possible failures lower the size of the file to 1KB by default instead of 1MB
**Testing:**
Will rely on GH CICD actions

[SYNPY-1319] Lower binary file size

---

tests/integration/synapseclient/test_evaluations.py

**Problem:**
https://sagebionetworks.jira.com/browse/SYNPY-816
Assertion error
**Solution:**
I enabled the test again
**Testing:**
I installed https://pypi.org/project/pytest-repeat/ and ran 100 times in parallel with 4 workers on my local machine

[SYNPY-816] Enable test_teams again

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_get_user_profile.py

**Problem:**
When a user calls the `getUserProfile` method with a username that is a number, the appropriate `UserProfile` is not retrieved. This essentially boils down to the fact that we currently allow people to pass `userName`s and `ownerId`s to `getUserProfile`, and that people are allowed to create usernames on Synapse that are just a string of numbers.
**Solution:**
Split `getUserProfile` into two separate functions. One that accepts `userName` as a string only, and one that only will accept an `ownerId` in the form of an integer.  
A complication of this solution is that `getUserProfile` is used in a number of places, some of which also allow `userName`s or `ownerId`s. This refactoring and the eventual deprecation of `getUserProfile` will need to be done in a future PR.

[SYNPY-1186] When a username is a number,  getUserProfile cannot retrieve the user

---

docs/articles/data_storage.rst

**Problem:**
The examples we had did not mention that the same folder can be used when migrating data to another S3 bucket. We also did not have a full comprehensive example
**Solution:**
I wrote a full script from start -> finish
**Testing:**
I verified that I could migrate a folder to an S3 bucket I created through the service catalog

[SYNPY-1337] Adding in a comprehensive example for migration to another S3 bucket

---

docs/articles/data_storage.rst

**Problem:**
1. When running a migration for multiple projects/folders you cannot re-use the same `.db` file as there is a check that will prevent overwriting data for previous indexes.
2. During long-running migrations we want to be notified on failure or success
**Solution:**
1. Adding a best practice to specify a unique name per project/folder to migrate
2. Added a syn.sendMessage to the script to notify on success or failure

[SYNPY-1337] Adding note about unique .db file

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

**Problem:**
When a file is being downloaded from an FTP link there is no indication that anything is occurring.
**Solution:**
Adding in a reporthook function that will print the transfer progress based on the block number, read size, and total size.
**Testing:**
1. I tested this out with a script similar to what tom added in the Jira:
```
syn = synapseclient.Synapse(debug=True)
syn.login()
file_ent = synapseclient.File(
"ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR197/048/SRR19761348/SRR19761348_1.fastq.gz",
name="SRR19761348_1.fastq.gz",
synapseStore=False,
parent="syn52569429",
)
file_ent = syn.store(obj=file_ent)
syn.get(entity=file_ent, downloadFile=True)
```
After running the script I get:
`Downloading  [--------------------]0.63%   9.0MB/1.4GB (3.1MB/s) …

[SYNPY-1333] Print transfer progress for FTP

---

.gitignore
synapseclient/core/utils.py
synapseutils/sync.py
tests/integration/conftest.py
tests/integration/synapseclient/integration_test_Entity.py
tests/integration/synapseclient/test_tables.py
tests/integration/synapseutils/test_synapseutils_sync.py
tests/unit/conftest.py
tests/unit/synapseclient/unit_test_annotations.py

**Problem:**
1. When a timestamp is given in a manifest.tsv file the current code is storing the data as a string annotation instead of a date.
2. When a datetime or date object is created we did not account for the timezone of the current machine or what is defined in the datetime object.
3. When the UTC timestamp was coming back from the synapse API the code was always converting the timestamp into local time, however, UTC time is what synapse is giving us.
**Solution:**
1. I added logic when creating timestamps from the manifest.tsv file to check the format of the string. If it matches a date format we are going to use that type in order to create the annotation.
2. I am taking into account the timezone of the current machine or, if defined, the timezone defined on the datetime object. …

[SYNPY-1358] Correction of timestamp in annotations from manifest file

---

synapseclient/api/annotations.py
synapseclient/models/__init__.py
synapseclient/models/annotations.py
synapseclient/models/file.py
synapseclient/models/folder.py
synapseclient/models/project.py
synapseclient/models/table.py
test_scripts/oop_poc_file.py
test_scripts/oop_poc_folder.py
test_scripts/oop_poc_project.py
test_scripts/oop_poc_table.py

**Problem:**
Working with annotations was previously requiring a lot more verbose information. I was forcing a Type to be defined.
**Solution:**
Using the same logic that is in the current python client convert based off the class types into the appropriate type for the Synapse REST API. This allows us to simply define a list or singular annotation.
**Testing:**
See the test scripts.

[SYNPY-1349] Detect annotation type

---

docs/articles/benchmarking.rst
docs/scripts/downloadBenchmark.py
docs/scripts/uploadTestFiles.py

**Problem:**
We had no stats on download times for varying file counts and sizes
**Solution:**
Create a benchmark script and ran on an EC2 instance created through the service catalog. This led to interesting information when starting to go into higher thread counts with > 1GB files. Something with the size of the files led to a lot of instability; As a result my recommendation was to not exceed the default thread count for these larger file sizes.

[SYNPY-1321] Download benchmark results

---

.coveragerc

**Problem:**
Our docs directory is going to hold test scripts used during tutorials and other one-off processes. We are not going to test these through unit/integration tests and should not count against our code coverage.
**Solution:**
Exclude the docs directory.
**Testing:**
This PR will serve as the test to verify that the docs directory is excluded from the coverage report.
The code coverage % is going up it looks like by around the amount I'd be expecting. Once merged I'll give in the metrics again to make sure it is updated in the `develop` branch.

omit the doc directory from code coverage

---

.github/workflows/build.yml

**Problem:**
1. We need to harden the pypi deployment strategy
2. We need to migrate away from using setup.py
**Solution:**
1. Implemented this GH action: https://github.com/pypa/gh-action-pypi-publish
2. Update to use `build` instead of running `setup.py`
**Testing:**
1. Verified that I could deploy artifacts out to test pypi. [This was uploaded without](https://test.pypi.org/project/synapseclient/3.2.1.1959/) the `setup.py` changes. [This was uploaded after](https://test.pypi.org/project/synapseclient/3.2.1.1961/) the `setup.py` changes.
2. I installed the artifacts via:
```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple synapseclient==3.2.1.1959
pip install --index-url https://test.pypi.org/simple/ --extra-index-url …
```

[SYNPY-1332] Pypi deployment strategy

---

docs/reference/core.md
synapseclient/annotations.py
synapseclient/core/retry.py
synapseclient/core/upload/multipart_upload.py
synapseclient/core/version_check.py
synapseclient/evaluation.py
synapseclient/wiki.py
synapseutils/sync.py

This PR will update the following documentation:
Should also add this to https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/docs/reference/core.md

[SYNPY-1370] Documentation Upgrade

---

mkdocs.yml
synapseclient/activity.py
synapseclient/core/remote_file_storage_wrappers.py
synapseclient/core/utils.py
synapseclient/entity.py
synapseclient/team.py

Problem:
1. Jenny had a great idea to move the initial setup to the home page instead of tutorials
2. Some links and formatting on a few pages was broken
Solution:
Implementing the changes
Testing:
Verified on docs site

[SYNPY-1371] Doc fixes

---

synapseutils/sync.py
tests/integration/synapseutils/test_synapseutils_sync.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

Problem:
A Manifest TSV with the following values were behaving differently when using the `syncToSynapse` function.
1. `[by,"values, by"]`
2. `[by, "values, by"]`
Using the `syncFromSynapse` was adding some excessive quoting to the content written in the manifest TSV. For example the data above was being written as: `"[by,""values, by""]"`
Solution:
1. Updating the logic around splitting of comma values to use regex instead of the CSV library as it did not handle for this.
2. Updated the logic in `syncFromSynapse` to not use quote characters in the TSV as it is not required. The result is that the example above will be stored as `[by,"values, by"]` in the TSV.
Testing:
1. Manually tested with the affected content.
2. Updated some integration tests for the problem case.
3. Added unit …

[SYNPY-1357] Correction to strip spaces before and after values

---

synapseutils/copy_functions.py

Importing `Entity` from `entity.py` was not working on Jupyter Notebook. This cell was executed after launching notebook off the latest `develop` branch on SynPy:
The solution was to have the type hints refer to the `Entity` class which is already imported at the top of `copy_functions.py` instead of calling it again from `synapseclient.entity.py`.
With this change there are no import errors for `synapseutils`:

[SYNPY-1412] Fixing typing issue in copy_functions

---

docs/reference/core.md
synapseclient/core/async_utils.py
synapseclient/models/annotations.py
synapseclient/models/file.py
synapseclient/models/folder.py
synapseclient/models/project.py
synapseclient/models/table.py

Problem:
1. The default OTEL decorator does not work as expected in Async environments. It will only capture when the method is created but not capture the entire execution of the method.
2. We were required to use a context manager in the function leading to more complex code.
Solution:
1. I created a new decorator that will allow us to decorate these class methods. In the future I'll plan to create other decorators for async functions too.
Testing:
1. I verified that the name of the functions were correctly shown:

Creating a decorator to be used in async class methods

---

synapseclient/core/async_utils.py

Problem:
Type hinting on functions wrapped in this decorator were not showing correctly.
Solution:
Remove type hinting
Testing:

Remove return type hinting on decorator

---

tests/unit/conftest.py

**Problem:**
1. The `synapse_client` parameter in the Synapse class is only initialized when using `login` - Which is ok for integration tests and normal operations, however, because we are not using `login` for unit tests I need to manually set the parameter
**Solution:**
Set the client in the `conftest.py` for unit tests
**Testing:**
Unit tests Brad/Bryan are developing

[SYNPY-1344] Set client in conftest since login is not used in unit tests

---

tests/unit/conftest.py

**Problem:**
Asynchronous function unit testing does not work in Windows GH Actions runners due to a [lack of support](https://github.com/python/cpython/issues/77589) for UNIX socket for Windows in Python. 
**Solution:**
Enable socket connections in unit tests on Windows systems.

[SYNPY-1344] Allows Socket Connections for Windows Systems in Unit Tests

---

synapseclient/activity.py
synapseclient/client.py
synapseclient/core/utils.py
synapseutils/sync.py
tests/integration/synapseclient/integration_test.py
tests/integration/synapseclient/test_command_line_client.py
tests/integration/synapseutils/test_synapseutils_sync.py
tests/unit/synapseclient/core/unit_test_utils.py

`syncToSynapse` fails for provenance pointing to a specific version of a synID using `syn[id].[version]` notation (e.g. `syn1234.5`). This revisits the discussion on the Python client adding support for synID`.[version]` notation.
---
The scope of this PR is constrained to allowing .version syntax in syncTo/FromSynapse `syn.get` and `synapse get` for the CLI
---
support for `syn.get(...)`  : 
support for `synapse get` for CLI : 
```
(synapsePythonClient) (synapseclient) bash-3.2$ synapse get syn53182713
Downloaded file: foo.txt
Creating /Users/jmedina/Documents/forks/synapsePythonClient/jout/foo.txt
(synapsePythonClient) (synapseclient) bash-3.2$ mv foo.txt foo_v2.txt
(synapsePythonClient) (synapseclient) bash-3.2$ synapse get syn53182713.1
Downloaded file: foo.txt
Creating …
```

[SYNPY-1398] Support `.[version]` syntax for input SynIDs

---

synapseclient/core/utils.py

Problem:
```
Traceback (most recent call last):
File "/home/bfauble/.local/share/virtualenvs/synapsePythonClient-17ZKsCr2/lib/python3.8/site-packages/mkdocs/livereload/__init__.py", line 193, in _build_loop
func()
File "/home/bfauble/.local/share/virtualenvs/synapsePythonClient-17ZKsCr2/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 67, in builder
build(config, live_server=None if is_clean else server, dirty=is_dirty)
File "/home/bfauble/.local/share/virtualenvs/synapsePythonClient-17ZKsCr2/lib/python3.8/site-packages/mkdocs/commands/build.py", line 322, in build
_populate_page(file.page, config, files, dirty)
File "/home/bfauble/.local/share/virtualenvs/synapsePythonClient-17ZKsCr2/lib/python3.8/site-packages/mkdocs/commands/build.py", line 175, in _populate_page …
```

[SYNPY-1398] Correct broken docstring

---

docs/reference/oop/models.md
docs/scripts/object_orientated_programming_poc/oop_poc_user_and_permission.py
synapseclient/client.py
synapseclient/models/__init__.py
synapseclient/models/file.py
synapseclient/models/folder.py
synapseclient/models/mixins/__init__.py
synapseclient/models/mixins/access_control.py
synapseclient/models/project.py
synapseclient/models/table.py
synapseclient/models/user.py
tests/integration/conftest.py
tests/integration/synapseclient/models/test_permissions.py
tests/integration/synapseclient/models/test_user.py
tests/unit/synapseclient/models/unit_test_user.py

**Problem:**
1. User profile and permissions need to be added to the OOP model
**Solution:**
1. Adding models to the client
**Testing:**
1. The sample script
2. Integration/unit tests

[SYNPY-1348] Add User profile and Permission models

---

synapseutils/walk_functions.py
tests/unit/synapseutils/unit_test_synapseutils_walk.py

**Problem:**
It was reported recently that running `synapseutils.walk` on large projects in Synapse with many folders and subfolders was taking a very long time due to `syn.get` being executed on every recursive `_helpWalk` call. Further, as pointed out by @linglp, this is unnecessary since we are also using `syn.getChildren` which provides the same information about entity types.
**Solution:**
Update `_helpWalk` to use the entities returned by `syn.getChildren` in the recursive function call. Specifically, repeated calls to `syn.get` are prevented by adding a new parameter that carries the starting entity into each recursive iteration. `syn.get` is called once per `walk` call to initiate the process from the parent folder or project.
Notes:
- A brief exploration was done to determine if …

[SYNPY-1411] Prevent Repeated `syn.get` calls in `_help_walk`

---

synapseclient/client.py
synapseclient/core/cache.py
synapseclient/core/upload/multipart_upload.py
synapseclient/core/upload/upload_functions.py
tests/integration/synapseclient/integration_test.py
tests/integration/synapseclient/integration_test_Entity.py
tests/unit/synapseclient/core/upload/unit_test_upload_functions.py
tests/unit/synapseclient/unit_test_client.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

**Problem:**
1. When there is a cache miss we never checked if the content of the file to be uploaded actually changed. As a result we would always upload the file to Synapse.
**Solution:**
1. If we need to upload a file to Synapse and the file already exists in Synapse and we got back an MD5 from Synapse compare the MD5 in Synapse to what the local file is - Is they are the same do not upload the file.
**Testing:**
1. Integration tests around this logic

[SYNPY-1253] Check MD5 before upload to verify change in content

---

synapseclient/models/file.py
synapseutils/copy_functions.py
tests/integration/synapseclient/models/test_file.py
tests/unit/synapseclient/models/unit_test_file.py

Problem:
Python client doesn't allow changing Synapse name for file metadata 
Solution:
Add a name argument to change_metadata in file.py and changeFileMetaData function in synapseutils
Testing:
Integration and unit testing are included in this PR

[SYNPY-448] allow changing Synapse name in changeFileMetaData

---

Pipfile.lock
setup.cfg

Problem:
1. We were locking the pandas dependency to <2.1
Solution:
1. Expanding the pandas range to allow any 2.x version - From a look at the change log there are no breaking changes here
2. Updating pipfile

[SYNPY-1326] Expand range for pandas dependency to <3.0

---

synapseclient/core/utils.py
synapseclient/models/folder.py
synapseclient/models/project.py
tests/integration/synapseclient/models/async/test_project_async.py
tests/integration/synapseclient/models/synchronous/test_project.py

**Problem:**
1. The usage of `asdict` was converting the folder/file dataclasses to a dict on the Project class - This pevented further code from calling methods on the Folder/File class.
```
File "/home/bfauble/BryansGreatWorkspace/synapsePythonClient/synapseclient/models/project.py", line 308, in store_async
await store_entity_components(
File "/home/bfauble/BryansGreatWorkspace/synapsePythonClient/synapseclient/models/services/storable_entity_components.py", line 80, in store_entity_components
folder.store_async(
AttributeError: 'dict' object has no attribute 'store_async'
```
**Solution:**
1. Only apply changes for modified items. We are not retrieving any dataclasses during the `get_async` calls [during this line](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/SYNPY-1443 …

[SYNPY-1443] Correct which fields are merged if there is a change

---

synapseclient/client.py
synapseclient/core/multithread_download/download_threads.py
tests/unit/synapseclient/core/multithread_download/unit_test_download_threads.py

**Problem:**
1. When retrieving a file from a storage location and we recieve an HTTP error (403 for example) we were failing in an unexpected location:
```
2024-02-26 10:27:30,985 [client:3044 - DEBUG]: 
Retrying download on error: [<class 'KeyError'>] after progressing 0 bytes
Traceback (most recent call last):
File "/home/bfauble/BryansGreatWorkspace/synapsePythonClient/synapseclient/client.py", line 3020, in _downloadFileHandle
downloaded_path = self._download_from_url_multi_threaded(
File "/home/bfauble/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "/home/bfauble/BryansGreatWorkspace/synapsePythonClient/synapseclient/client.py", line 3092, in _download_from_url_multi_threaded
multithread_download.download_file(self, request) …
```

[SYNPY-1445] Raise exception on HTTP error when retrieving file from storage location

---

.github/workflows/build.yml
Pipfile.lock
docs/reference/client.md
docs/reference/rest_apis.md
mkdocs.yml
setup.cfg
synapseclient/api/__init__.py
synapseclient/api/entity_bundle_services_v2.py
synapseclient/client.py
synapseclient/core/async_utils.py
synapseclient/core/exceptions.py
synapseclient/core/retry.py
tests/integration/conftest.py
tests/integration/synapseclient/integration_test.py
tests/unit/synapseclient/core/unit_test_retry.py

**Problem:**
1. The default requests library does not contain any async interfaces
2. The back-off was not sufficient and the retry logic needs some TLC
**Solution:**
1. Adding the HTTPX dependency
3. Creating 2 new async client instances in Synapse that can be used to interact with Synapse or the Storage Providers
4. Creating a new API class with async interfaces that work directly with the the [EntityBundleV2Controller](https://rest-docs.synapse.org/rest/#org.sagebionetworks.repo.web.controller.EntityBundleV2Controller)
5. I re-wrote our exponential back-off logic to follow: 1ms + random(10ms-100ms). The 1ms is exponentially backed off by a factor of 2 for each retry and the random is not touched.
6. Updated retry logic to not fail based on the number of retries, instead fail after a …

[SYNPY-1419] Httpx async client

---

synapseclient/core/cache.py
tests/unit/synapseclient/core/unit_test_Cache.py

**Problem:**
1. In the cache if a cache value was a dictionary but it did not contain the exact key of `modified_time` the code would return back the parent dict - causing further code to fail that was expecting a string to be returned.
**Solution:**
1. Adding a guard statement in `_get_cache_modified_time` that verified that the data returned is going to be a string or the value for `modified_time`
**Testing:**
Added unit tests around the logic that verify the behavior if the cache map:
1. Is a dict but does not contain `modified_time` key
2. Is a dict but contains neither of the expected keys
3. The entry is an empty dict
4. The entry is None

[SYNPY-1453] Guard around modified time item in cache

---

synapseclient/client.py
synapseclient/core/retry.py
synapseclient/core/upload/multipart_upload_async.py
synapseclient/core/upload/upload_functions_async.py
synapseclient/core/utils.py
synapseclient/models/annotations.py

**Problem:**
1. OTEL span were a bit all over the place with varying depth and information
**Solution:**
1. Focus OTEL spans on the I/O portions of the application to know when requests are start/stopping or long running MD5 calculations are taking place
**Testing:**
1. Verified by running the upload benchmark script and checking a Jaeger container deployed on my local:

[SYNPY-1420] Clean up otel spans

---

synapseclient/client.py
synapseclient/models/file.py
synapseutils/sync.py

**Problem:**
1. The sync util function had a mechanism to limit the number of files that can enter the store process.
**Solution:**
1. Adding a semaphore to the client.
2. Moving code from the sync function into the File.store_async() function that wraps the upload method. Now only a limited amount of files can enter into the "uploading" state.
**Testing:**
I tested out storing a few different data sizes.
1000/1GiB: 125.61s
1/10GiB: 170.75s
100/10GiB: 156.92s
These numbers are in-line with the bench marked numbers collected on the table here: https://github.com/Sage-Bionetworks/synapsePythonClient/blob/620937a91398a2446b0483619ae88a15adede3f8/docs/explanations/benchmarking.md#some-insights

[SYNPY-1356] Moving file semaphore under file store

---

synapseclient/client.py
synapseclient/core/credentials/credential_provider.py

**Problem:**
The order of credentials being tried was incorrect in the comment
**Solution:**
Correct the comment to match the code from: https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/synapseclient/core/credentials/credential_provider.py#L258

[SYNPY-1474] Correct order of credentials in comment

---

.github/workflows/build.yml

Problem:
****
1. Running integration tests in ubuntu-22.04 takes between 3-4 hours to complete.
**Solution:**
1. Revert ubuntu versions for the GH runner
**Testing:**
1. Verified after this change that a pipeline run only took ~30 minutes to complete

[SYNPY-1456] Revert to old ubuntu

---

synapseclient/__init__.py
synapseclient/__main__.py

Problem:
In the datawarehouse, the client version isn’t being parsed for user_agent of the synapse command line client
Solution:
Update the user agent of the  synapse command line client by removing the `synapseclient` substring with empty string so the client version can be pulld by Synapse-ETL-Jobs
Testing:
Passed both unit test and integration test

[SYNPY-1466] update user agent for command line 

---

.github/workflows/build.yml

Problem:
Currently, sonarcloud only executes when tests pass, but even if tests fail, it's valuable for sonarcloud to execute.
Solution:
Let SonarCloud scan always run no matter what status of the previous steps. Add a separate step to check if coverage report exist, if not, skip downloading coverage report. Run `Override Coverage Source Path for Sonar`, only if the coverage report download step has succeeded. 
Testing:
1. Skip downloading the coverage report when the coverage report does not exist
2. The SonarCloud scan runs even though `Override Coverage Source Path for Sonar` fails.
3. Skip Override Coverage Source Path for Sonar when the coverage report does not exist.

[SYNPY-1470] Remove SonarCloud's dependency on test job

---

.github/workflows/build.yml
Dockerfile

_We recently added a GHCR [image](https://github.com/orgs/sage-bionetworks/packages/container/package/synapsepythonclient) for the python client because there was no up-to-date image hosted anywhere. We should add a step to the CI workflow to publish new versions of the client as docker images automatically when a new version is released._
Two new jobs (`ghcr-build-and-push-on-merge`, `ghcr-build-and-push-on-develop`) are created to build a multi-platform image of the repository and push it to the GitHub Container Registry.
`ghcr-build-and-push-on-release`
~~- [ ] The docker image should be multi-platform (AMD64, ARM64)~~
`ghcr-build-and-push-on-develop`
~~- [ ] The docker image should be multi-platform (AMD64, ARM64)~~
`ghcr-build-and-push-on-release`
I manually fed a version …

[SYNPY-1341] Add CI step to containerize and upload synpy to the GHCR

---

.github/workflows/build.yml

**_problem 1)_** The latest `v4.3.0` release did not trigger the CI job written to push the latest `synapsepythonclient` package to the GHCR.
_**problem 2)**_ It would be nice to have a pre-release image before an official release that validators can use to verify functionality is working as expected
_**RE: problem 1)**_
_**RE: problem 2)**_
pre-release: https://github.com/Sage-Bionetworks/synapsePythonClient/releases/tag/v0.0.0-rc
package: https://github.com/Sage-Bionetworks/synapsePythonClient/pkgs/container/synapsepythonclient/224686708?tag=v0.0.0-rc-prerelease

[SYNPY-1341 & SYNPY-1479] Change syntax for conditional of ghcr release job

---

synapseclient/core/credentials/credential_provider.py

**Problem:**
1. There have been 2 service desk tickets from folks unable to use `synapse login -p $AUTH_TOKEN` due to having a synapse config that might not have the appropriate data.
**Solution:**
1. Updating the credential chain to use CLI arguments first
**Testing:**
1. Verified that setting `-p` is used if supplied, but not if not supplied:

[SYNPY-1483] Update default order for credential provider

---

synapseclient/api/__init__.py
synapseclient/api/annotations.py
synapseclient/models/annotations.py

**Problem:**
1. Storage of annotation was taking place in a loop executor
**Solution:**
1. Updating logic to be stored without the executor/other threads
**Testing:**
1. Unit/Integration tests

[SYNPY-1482] Updating to remove loop executor during annotation store

---

.pre-commit-config.yaml

Related to: [SYNPY-1485 Include isort with pre-commit](https://sagebionetworks.jira.com/browse/SYNPY-1485?atlOrigin=eyJpIjoiY2U1NjZkNGRkZDhhNDk5Yzg1YTkwMmVjN2I5ZjdiZjIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
Run `pre-commit install`

[SYNPY-1485] feat: added isort to pre-commit hook

---

synapseclient/table.py

User received a `FutureWarning` from pandas v2.2.1 notifying them of a future syntax issue in the way dataframe columns are updated in the python client's `table.py` script.
The message:
```
FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
```
Improve the logic in `table.py` that replaces `NaN`s or `NA` values for a given column `col` …

[SYNPY-1447] Update `fillna` method to work directly off original df

---

.github/workflows/build-docs.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
tests/integration/synapseclient/test_tables.py

We are using versions of GitHub actions that still use`Node.js 16`, which is now deprecated and leads to deprecation warnings in the builds. This clutters build output messages which is unhelpful when troubleshooting/monitoring the status of your builds.
Latest run: https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/9618137457
UPDATED:
Latest run: https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/9620252513

[SYNPY-1457] Fix deprecated Node.js build warnings

---

.github/workflows/build.yml
synapseclient/.synapseConfig

The synapse python client’s coverage reports are not being found (see [thread here ](https://github.com/Sage-Bionetworks/synapsePythonClient/pull/1112#discussion_r1651470850)for more context) and code coverage is not being monitored:
For testing I repeated some of the tests done in https://github.com/Sage-Bionetworks/synapsePythonClient/pull/1095
----
----

[SYNPY-1487] Fix missing coverage report

---

.github/workflows/build.yml

**Problem:**
The workflow runs for check-deploy have been failing with:
check-deploy (macos-11, 3.10)
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
**Solution:**
1. Updating image versions
**Testing:**
1. Will be testing on next check deploy run

Update os matrix for check-deploy

---

synapseclient/core/download/download_async.py
synapseclient/core/exceptions.py
synapseclient/core/retry.py

**Problem:**
1. If an HTTP error occurred during the part streaming we fail in some code that was expecting the content of the message to be available:
```
Failed downloading syn59063792 to /root/.synapseCache/60/140032060/PEGS_methylation_beta_train_synthetic.rds.synapse_download_140032060                   Traceback (most recent call last):
File "/synapsePythonClient/synapseclient/core/download/download_async.py", line 346, in _execute_download_tasks
start_bytes, end_bytes = completed_task.result()
File "/synapsePythonClient/synapseclient/core/download/download_async.py", line 417, in _stream_and_write_chunk_wrapper
return await loop.run_in_executor(
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File …
```

[SYNPY-1476] Skip reading response content on error

---

docs/scripts/object_orientated_programming_poc/oop_poc_file.py
synapseclient/models/file.py
synapseclient/models/mixins/storable_container.py
synapseclient/models/protocols/file_protocol.py
synapseutils/sync.py
tests/integration/synapseclient/core/test_download.py
tests/integration/synapseclient/core/test_external_storage.py
tests/integration/synapseclient/models/async/test_file_async.py
tests/integration/synapseclient/models/synchronous/test_file.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

**Problem:**
1. When working with the File model you needed to specify a `download_location` parameter when using the `.get()` function, but `path` when using the `store()` function. This was a bit confusing.
**Solution:**
1. Updating logic such that only the path parameter is needed on the file for either operation.
**Testing:**
1. Some manual testing to verify getting a file already on disk, not on disk, and on disk - but downloading to another directory

[SYNPY-1504] Remove `download_location` from File and rely only on Path

---

synapseclient/core/retry.py
tests/integration/synapseclient/core/test_download.py

**Problem:**
1. In https://sagebionetworks.jira.com/browse/SYNSD-1127 - Some exceptions were raised in the HTTPX library that the retry function was not accounting for.
**Solution:**
1. Adding the class name of the exceptions we're now looking for.
**Testing:**
1. I added some temporary debug code to verify that an individual part is the only thing retried, not an entire file
2. Added an integration test around the logic change

[SYNSD-1127] Retry on several more exceptions for transfers

---

docs/tutorials/python/file.md

**Purpose:** Small PR. Just added a missing line of code to the file tutorial in section: [List all Folders and Files within my project](https://python-docs.synapse.org/tutorials/python/file/#3-list-all-folders-and-files-within-my-project)
**Testing:** Ran `mkdocs` locally and see change below:
- Before:
- After:

Update file tutorial with missing line

---

synapseclient/client.py
synapseclient/core/download/download_async.py
synapseclient/core/download/download_functions.py
synapseclient/core/transfer_bar.py
tests/integration/synapseclient/integration_test.py
tests/integration/synapseclient/test_command_line_client.py
tests/integration/synapseclient/test_evaluations.py
tests/unit/synapseclient/core/unit_test_download.py
tests/unit/synapseclient/core/unit_test_sts_transfer.py
tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py
tests/unit/synapseclient/unit_test_Entity.py
tests/unit/synapseclient/unit_test_Wiki.py
tests/unit/synapseclient/unit_test_client.py
tests/unit/synapseclient/unit_test_tables.py

**Problem:**
1. Around 8 months ago I had added in logic to cache the logged in synapse client instance as a class variable to prevent the need from passing your instance into all methods. There were a few internal methods that I missed when setting up the download logic leading to issues where `.login()` was not called.
**Solution:**
1. Correct the missing propagation.
2. Updating the cache logic to cache in the class init rather than on login
**Testing:**
1. Tested locally to connect and query on an anonymously accessible table
2. Integration tests

[SYNPY-1511] Correct missing synapse client propogation and caching

---

synapseclient/core/download/__init__.py
synapseclient/core/download/download_async.py
synapseclient/core/download/download_functions.py
synapseclient/core/retry.py
tests/integration/synapseclient/core/test_download.py
tests/integration/synapseclient/core/test_external_storage.py
tests/unit/synapseclient/core/unit_test_download.py
tests/unit/synapseclient/unit_test_client.py

**Problem:**
Due to the unordered nature of AsyncIO executing tasks async, when there is a large queue of files to download, the file may not be downloaded for a while after a pre-signed URL is retrieved. This shows up as a `403 Forbidden` error which needs to be handled for these cases to prevent downloads from failing.
**Solution:**
Update `download_from_url` to handle these `403` responses and try again by checking if the URL is expired when we receive a 403 response code, retrieving a new URL and retrying the download.
**Testing:**
- This was tested by:
1. Reproducing the error faced by a [user](https://sagebionetworks.jira.com/browse/SYNSD-1188) by using the `random` package to have this failure occur.
2. Hard-coding an expired URL into the code and running a `synapse get` CLI …

[SYNPY-1514] Handle Expired Pre-Signed URLs

---

synapseclient/table.py
tests/unit/synapseclient/unit_test_tables.py

**Problem:**
In #1127, I added the ability to pass `pandas.read_csv` keyword arguments to `CsvFileTable.asDataFrame` to give users the ability to have more control over the dataframe that was produced (such as determining which values should be treated as NA). An unintended side-effect of this was that users could unintentionally pass a keyword argument that is already set in the code that calls `read_csv` in `_csv_to_pandas_df`, causing an error like this one:
```
446 # "ValueError: Only length-1 line terminators supported"
--> 447 df = pd.read_csv(
448     filepath,
449     dtype=dtype,
450     sep=separator,
451     lineterminator=line_terminator if len(line_terminator) == 1 else None,
452     quotechar=quote_char,
453     escapechar=escape_char,
454     header=0 if contain_headers …
```

[SYNPY-1521] Fixes `asDataFrame` `kwarg` Collision Issue

---

.github/workflows/build.yml
Pipfile
Pipfile.lock
setup.cfg
synapseclient/core/download/download_functions.py
tests/integration/synapseclient/core/test_external_storage.py
tests/integration/synapseutils/test_synapseutils_copy.py
tests/unit/synapseutils/unit_test_synapseutils_copy.py
tests/unit/synapseutils/unit_test_synapseutils_migrate.py
tests/unit/synapseutils/unit_test_synapseutils_sync.py

**Problem:**
1. Python 3.12 is not officially supported for this project
**Solution:**
1. Updating the build steps to also run on python 3.12
**Testing:**
1. Tested via integration/unit tests
2. I went throw each of the python tutorial written up https://python-docs.synapse.org/tutorials/python/project/ and verified I could complete them while running Python 3.12.6 in Ubuntu on WSL2 on a windows host.

[SYNPY-1520] Support python 3.12

---

.github/workflows/build.yml

**Problem:**
When I merged #1134, the `ghcr-build-and-push-on-develop` step of the CI workflow [failed](https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/11043502633/job/30677883684). This appears to be because there was no Python version specified for this workflow step and the Actions runner defaulted to 3.8 which prevented `synapseclient` from being able to be installed.
**Solution:**
I added steps to specify the Python version for both `ghcr-build-and-push-on-develop` and `ghcr-build-and-push-on-release` which shoule hopefully allow the workflow to work for both types of GHCR publishing.
**Testing:**
It is difficult to test these changes because these CI workflow steps are only triggered on release (or push to `develop`) and I don't really want to force a fake …

[SYNPY-1524] Fixes `ghcr-build-and-push-on-develop` and `ghcr-build-and-push-on-release` Workflows

---

.github/workflows/build.yml
Dockerfile

I realized after merging #1136  that it was the Python version in the Dockerfile that was causing this error, not the Action runner. I reproduced the [issue](https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/11055829020/job/30715915471) by trying to build the container locally and got the same error:
```
Dockerfile:18
--------------------
16 |     COPY . .
17 |     
18 | >>> RUN pip install --no-cache-dir .
19 |     
20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir ." did not complete successfully: exit code: 1
```
But, I was able to successfully build the container after switching the base image to `python:3.9-slim` so that the Python version is set before installing the other dependencies.

[SYNPY-1524] Updates `Dockerfile`

---

synapseclient/core/download/download_async.py
synapseclient/core/download/download_functions.py
tests/unit/synapseclient/core/download/unit_test_download_async.py
tests/unit/synapseclient/core/unit_test_download.py

**Problem:**
1. Fixes #1138
**Solution:**
1. Verify presence of query param in URL
**Testing:**
1. Manually tested with a google backed item that it could be downloaded

[SYNPY-1525] Verify expiration param in url

---

synapseclient/client.py
synapseclient/core/utils.py
tests/integration/synapseclient/test_evaluations.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/unit_test_client.py

The endpoint `evaluation/submission/{id}` was receiving communications with submission IDs that had decimal points in them (e.g. `123.0`). This was obstructing an ingestion process in Snowflake, and should not exist in the first place. Submission IDs are not ID types that support decimal points.
In `getSubmission(...)` and other related methods in `client.py`, the `id_of(...)` method from `utils.py` is utilized to retrieve a valid entity ID. This method was being used for submission IDs, but was effectively useless, as it would just return the same string object or numbers object (as a string) without verifying its format.
The solution involves creating a separate method called `validate_submission_id` and replacing `id_of` with it, to enforce the no-decimal rule in the input.
```
In [1]: …
```

[SYNPY-1513] Validate input submission ID in `getSubmission(...)`

---

docs/tutorials/installation.md

A `conda` user reported issues with `synapseclient` not working until `LD_LIBRARY_PATH` was specified on their system.
I re-compiled the docs to preview what this change will look like on the website

[SYNPY-1522] Add note on lost shared libraries to install instructions for `conda`

---

synapseclient/core/credentials/credential_provider.py

**Problem:**
1. When the user ID is retrieved the data is not added to any trace, by providing this information we can use telemetry data to track a user action in the data.
**Solution:**
1. When the credentials are retrieved attach the user.id if the span is being recorded.
**Testing:**
1. I verified that the data is being passed along as expected:

[FDS-2458] Attach the user.id of the logged in user to the trace span

---

docs/tutorials/python/download_data_in_bulk.md

The live documentation site was pointing to incorrect sections of the tutorial script
Fix that

Update misaligned script

---

Dockerfile

This pull request includes a small change to the `Dockerfile`. The change adds the `procps` package to the list of installed packages. `ps` from `procps` is required by Nextflow. There are many use cases where having auto-built, latest version of synapsePythonClient in a Docker container will be valuable for users.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R7): Added `procps` to the list of installed packages.

Add procps to Dockerfile to enable use of container in Nextflow

---

synapseclient/models/agent.py
synapseclient/models/mixins/asynchronous_job.py

@BWMac and I are working together to discuss ways in which we will implement this feature

[SYNPY-1544] potential changes to mixin

---

synapseclient/models/agent.py
synapseclient/models/protocols/agent_protocol.py

The feature allowing the Synapse Agent to create annotations has been disabled indefinitely. We should therefore not include this example usage in the `Agent` model.

Removes example setting annotations with Agent class

---

synapseclient/models/agent.py
synapseclient/models/protocols/agent_protocol.py

**Problem:**
1. When calling the `prompt` function it was a bit awkward to get the response out of the chat history in order to programmatically use the result.
**Solution:**
1. Return back the AgentPrompt when calling the `prompt` function
**Testing:**
1. I manually verified that I was getting back the expected object from the prompt call

[SYNPY-1544] Return the AgentPrompt when calling the prompt function

---

synapseclient/client.py
synapseclient/wiki.py
tests/integration/synapseclient/test_wikis.py
tests/unit/synapseclient/unit_test_Wiki.py

**Description:**
A user reported an unhandled error when trying to store a Wiki object in Synapse like so (where syn123 is instead a valid Synapse project ID that the user has access to):
```
from synapseclient import Wiki
foo = Wiki(owner="syn123", title="test", parentWikiId="")
syn.store(foo)
```
This happened because the API does not treat that value of `parentWikiId` like a `None` value and instead throws an error. To prevent that error from happening, I added logic in `Wiki.__init__` that converts any falsey value that is provided for `parentWikiId` to `None`. 
Additionally, the user was receiving this error message:
```
AttributeError: 'SynapseHTTPError' object has no attribute 'message'
```
rather than a message passed on from the API which I addressed by …

[SYNPY-1547] `parentWikiId=""` Bug

---

Dockerfile

I realized because of an error encountered by an `nf-synapse` user that the newer versions of the `synapseclient` docker container do not have `pandas` installed properly.
This issue was caused by mixing `apt-get` installing `python3-pandas` with a base Python image. The problem being that Python packages installed via `apt-get` don't automatically integrate with the Python environment from the Docker base image. Fortunately we have a `pandas` extra built into `setup.cfg`, so I switched to installing it that way.
Built the container locally, started up a Python terminal inside of it, and ran `import pandas`. If you do this with `sagebionetworks/synapsepythonclient:v4.7.0` you get an import error.

Update Dockerfile - Fixes `pandas` installation

---

.github/workflows/build.yml
CONTRIBUTING.md
README.md
setup.cfg
synapseclient/core/utils.py

**Problem:**
1. Python 3.13 is not supported
**Solution:**
1. Update the github pipeline to build 3.13 and run integration tests on that version.
2. Updating the docs and install files to reference 3.13 as a valid version.
3. Removing the usage of `cgi.parse_header` in favor of the `email.message` `Message` class as mentioned in (PEP 594) https://docs.python.org/3/whatsnew/3.13.html#removed-modules-and-apis
**Testing:**

[SYNPY-1553] Update to support python 3.13

---

docs/tutorials/file_versioning.md
docs/tutorials/tables.md

There were some missing code lines, and lines that produced errors in the [Table](https://python-docs.synapse.org/tutorials/tables/#tables) and [File Versioning](https://python-docs.synapse.org/tutorials/file_versioning/) tutorials
See this [validation results report for another ticket](https://sagebionetworks.jira.com/browse/SYNPY-1552?focusedCommentId=239464) for more info
- Added missing setup lines
- Replaced lines throwing errors with corrected lines of code
Tested with `mkdocs serve` locally. 
See example change with file versioning tutorial
Before
After
See  example change with tables tutorial
Before
After

Add table and file versioning tutorial updates

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

**Problem:**
1. When making HTTP requests with the HTTPX library, we were incorrectly including the User-Agent header from the Python 'requests' package instead of using HTTPX's own User-Agent.
2. It was cumbersome for users to specify their own additional `User-Agent` fields to add to the HTTP requests.
**Solution:**
1. Replacing the `requests` package `User-Agent` header for requests that are using the HTTPX library.
2. Provide a class argument for the `Synapse` class that allows users to specify their own `User-Agent` headers to add.
**Testing:**
1. Unit testing the logic for both creating valid/invalid headers, along with verifying that the headers are correct getting added on the outbound requests for the `requests` and `httpx` library.

[SYNPY-1570, SYNPY-1555] Support passing `user_agent` to the Synapse class constructor, and HTTPX Library usage

---

synapseclient/models/mixins/asynchronous_job.py
synapseclient/models/mixins/table_operator.py

**Problem:**
1. When changes are made to a view in Synapse an eventually consistent process is kicked off in order to bring that view up to date. If you query the view directly after the changes are made you will not see your changes reflected in that view.
**Solution:**
1. During the upsert method call allow users to specify if they would like to wait for their changes to show up in the view before returning control.
**Testing:**
1. I wrote an integration test (For FileViews that are not yet committed) to verify the functionality before and after

[SYNPY-1575] Support waiting for evetually consistent view after changes are made

---

.github/workflows/build.yml

**Problem:**
1. The integration tests for the SYNPY client take a very long time to run, and even longer so when a single feature branch is running multiple sets of tests. Currently, every commit would cause the tests to run and no previous runs are getting cancelled.
**Solution:**
1. Using a [concurrency group](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency) I am causing previous build jobs to be cancelled if there is a new commit pushed to the branch.
**Testing:**
1. I verified after pushing a new commit to this feature branch that the existing action was cancelled:
2. https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/13707998334

Prevent concurrent builds per branch

---

synapseclient/__main__.py
synapseclient/client.py
synapseclient/core/cumulative_transfer_progress.py
synapseclient/core/remote_file_storage_wrappers.py
synapseclient/core/transfer_bar.py
synapseclient/core/upload/multipart_upload.py
synapseclient/core/upload/multipart_upload_async.py
synapseclient/core/utils.py
synapseclient/models/mixins/table_operator.py
synapseutils/describe_functions.py
synapseutils/monitor.py
synapseutils/sync.py
tests/unit/synapseclient/core/unit_test_cumulative_transfer_progress.py
tests/unit/synapseclient/core/unit_test_remote_storage_file_wrappers.py
tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py
tests/unit/synapseutils/unit_test_synapseutils_describe.py

**Problem:**
1. Nested TQDM progress bars by default overwrite other progress bars. This leads to loss of information and poor looking logs.
2. There are a significant number of print, and sysout messages getting printed to the console. When messages are printed in this way then it will break the formatting of the tqdm progress bar.
**Solution:**
1. Updating the TQDM progress bars to include `leave=None`. This makes it so the behavior for the progress bars it to be removed if it isn't the highest level parent progress bar. It cleans up the bars significantly.
2. Updating many print and sysout messages to use the synapse class logger to print out exceptions, warnings, and info messages.
**Testing:**
1. The following are 2 short clips that show the console log during the creation, querying, …

[SYNPY-1488] Patch nested tqdm progress bars and messages to logger

---

.readthedocs.yaml

- There are a few settings set on the read the docs side that could use a slight update.
- Update the OS and the python version used so that it's unlikely that we are soon to fall behind in supported versions.
- Update search ranking to put the API reference docs lower, this is so that if a user searches for something they are likely to see the tutorial documents first.
- Will be testing in this PR/branch https://app.readthedocs.org/projects/synapsepythonclient/builds/27555367/
Verified:
1. python version: `global python 3.13.0`
2. The updated OS was used: `"os": "ubuntu-22.04",`
3. Search ranking is putting reference docs lower:

[SYNPY-1542] Upgrade readthedocs os, python version, and search ranking

---

synapseclient/client.py
tests/unit/synapseclient/unit_test_client.py

- Integration tests can hang for reasons that I do not understand, and they will only timeout after the 6 hour limit is finally reached.
- Based on [this documentation](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts): 
> Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner. By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more.
Due to this what I suspect is occurring:
1. An HTTP request is sent to Synapse
2. A connection error occurs, but a message is not sent back to the SYNPY client code
3. The SYNPY client code hangs forever because it did not get a message back, AND, it never hits a timeout because there is no …

Include a default timeout for HTTP requests library to 70 seconds

---

docs/reference/experimental/async/materializedview.md
docs/reference/experimental/sync/materializedview.md
docs/tutorials/python/materializedview.md
docs/tutorials/python/tutorial_scripts/materializedview.py
mkdocs.yml
synapseclient/api/entity_factory.py
synapseclient/core/constants/concrete_types.py
synapseclient/models/__init__.py
synapseclient/models/materializedview.py
synapseclient/models/mixins/table_components.py
tests/integration/synapseclient/models/async/test_materializedview_async.py
tests/integration/synapseclient/models/synchronous/test_materializedview.py

- The https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/table/MaterializedView.html concept does not exist in the OOP mode
- Create the MaterializedView class, a tutorial for the changes, and a bunch of different examples
- Manual testing to verify the changes behave as expected
- A tutorial to showcase the model
- Integration tests verifying the changes
**Links to resources:**
1. Tutorial: https://synapsepythonclient--1190.org.readthedocs.build/en/1190/tutorials/python/materializedview/
2. Sync API Reference: https://synapsepythonclient--1190.org.readthedocs.build/en/1190/reference/experimental/sync/materializedview/
3. Async API Reference: https://synapsepythonclient--1190.org.readthedocs.build/en/1190/reference/experimental/async/materializedview/

[SYNPY-1579] Introduce the materialized view

---

synapseclient/client.py
synapseclient/core/version_check.py
tests/integration/synapseclient/core/test_version_check.py
tests/integration/synapseclient/integration_test.py
tests/unit/synapseclient/core/unit_test_utils.py
tests/unit/synapseclient/core/unit_test_version_check.py

[SYNPY-1497]
When checking the Python version, `synapseclient.core.version_check.version_check` GitHub was being used to find the latest version. This caused a problem when a version had been pushed into the master branch, but hadn't been updated in Pypi yet.
In addition, while working on this, I found a bug. To compare package versions, the code converts the current and latest versions by spliting them into tuples where each version level is a string. For example, the current version of the client is "4.7.0". This gets converted into a tuple like: `("4", "7", "0')` . These tuples then get comapred: `("4", "6", "9') < ("4", "7", "0')` When tuple comparisons happen the first elements of each are compared, and if those are equal then second elements are compared and so on. 
The problem is …

[SYNPY-1497] refactored version check to use Pypi for version info

---

synapseclient/core/upload/upload_utils.py
synapseclient/models/mixins/table_components.py
tests/integration/synapseclient/models/async/test_table_async.py

- In the loop over the Pandas DataFrame to return the bytes for upload into Synapse -- a `.tell()` was not performed after we dropped the X number of bytes from the BytesIO buffer
- When the first chunk of the DataFrame was being written the bytes in the buffer from the header of the DataFrame was causing data to be dropped (Sometimes silently) from the end of the first chunk. In one case there was around 20 missing bytes from a large-text column.
- Bytes from the header were getting skipped at the front of the very first DataFrame
- After dropping bytes from the front of the buffer call `.tell()` to re-read `number_of_bytes_in_buffer`
- Removing writing the header to the buffer, instead use the `bytes_to_prepend` argument instead
- Don't skip bytes in the offset for the header, instead …

[SYNPY-1584] Add a buffer.tell when truncating bytes during dataframe upload and drop writing header to csv

---

.github/workflows/build.yml
docs/reference/experimental/async/virtualtable.md
docs/reference/experimental/sync/virtualtable.md
docs/tutorials/python/tutorial_scripts/virtualtable.py
docs/tutorials/python/virtualtable.md
mkdocs.yml
synapseclient/api/entity_factory.py
synapseclient/core/constants/concrete_types.py
synapseclient/core/exceptions.py
synapseclient/models/__init__.py
synapseclient/models/mixins/table_components.py
synapseclient/models/virtualtable.py
tests/integration/synapseclient/models/async/test_virtualtable_async.py
tests/integration/synapseclient/models/synchronous/test_virtualtable.py
tests/unit/synapseclient/models/unit_test_virtualtable.py

We did not previously have an OOP model representing the Synapse [VirtualTable](https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/table/VirtualTable.html). We should follow the example of the MaterializedView to implement this model, with the exception that JOIN and UNION operations are not supported in the `definingSQL` of `VirtualTable`s.
Implemented the `VirtualTable` model, all expected functionality, updated documentation, added a tutorial and examples. Followed #903 as an example because there is a lot of overlap in functionality with `MaterializedView`s.
Tested implementation by manually running the code, wrote integration tests and unit tests as needed.
There was a compatibility issue causing failures in our CI pipeline with older versions of `pip` so I added a …

[SYNPY-1580] Adds `VirtualTable` OOP Model

---

docs/reference/experimental/async/dataset.md
docs/reference/experimental/async/dataset_collection.md
docs/reference/experimental/async/entityview.md
docs/reference/experimental/async/file.md
docs/reference/experimental/async/folder.md
docs/reference/experimental/async/materializedview.md
docs/reference/experimental/async/project.md
docs/reference/experimental/async/table.md
docs/reference/experimental/async/virtualtable.md
docs/reference/experimental/sync/dataset.md
docs/reference/experimental/sync/dataset_collection.md
docs/reference/experimental/sync/entityview.md
docs/reference/experimental/sync/file.md
docs/reference/experimental/sync/folder.md
docs/reference/experimental/sync/materializedview.md
docs/reference/experimental/sync/project.md
docs/reference/experimental/sync/submissionview.md
docs/reference/experimental/sync/table.md
docs/reference/experimental/sync/virtualtable.md
synapseclient/api/__init__.py
synapseclient/api/entity_services.py
synapseclient/client.py
synapseclient/models/mixins/access_control.py
synapseclient/models/protocols/access_control_protocol.py
tests/integration/synapseclient/models/async/test_permissions_async.py
tests/integration/synapseclient/models/synchronous/test_permissions.py
tests/unit/synapseclient/models/async/unit_test_permissions_async.py
tests/unit/synapseclient/models/unit_test_permissions.py

https://sagebionetworks.jira.com/browse/SYNPY-1244
- When sharing subfolders or specific files with collaborators in private projects, permissions create a complex ACL (Access Control List) structure where:
- Sharing settings can be hidden deep in folder hierarchies
- Files don't automatically inherit the parent container's permissions
- When releasing data, these individual ACLs need to be removed so files properly inherit parent container sharing settings
- There was no mechanism available to delete ACLs in the OOP model, nor was there a way to recursively delete the ACL
- Adds new functions to recursively reset permissions on entities within a container
- Implements functionality to determine if an entity inherits ACLs from its parent
- Works with nested folder structures to ensure …

[SYNPY-1244] Add delete permissions/acl functionality

---

synapseclient/models/mixins/access_control.py
synapseclient/models/protocols/access_control_protocol.py
tests/integration/synapseclient/models/async/test_permissions_async.py
tests/integration/synapseclient/models/synchronous/test_permissions.py
tests/unit/synapseclient/models/async/unit_test_permissions_async.py
tests/unit/synapseclient/models/unit_test_permissions.py

- The docstring for the `recursive` flag implied incorrect behavior of the function when used in conjunction with `include_container_content`
- Update docstring and examples to clarify behavior
- Raise a ValueError exception when falling into a situation that will cause no actions to be taken
- Verified updated behavior and unit test

[SYNPY-1244] Clarify docstrings with `delete_permissions` function and `recursive` behavior

---

synapseclient/core/async_utils.py

When client functionality was called by a user and wrapped in a `try: catch:` block, the exception was caught but the exception trace was still displayed. This behavior was undesirable by the user who expected no trace to be displayed since she had implemented her own error handling.
The functionality in the wrapper that logs and raises exceptions was removed to allow exceptions raised in wrapped async methods to be handled by the caller or within the client by the interpreter instead of having an intermediary that always logs and raises exceptions, which is undesirable by some users
testing was done with a mre adapted from the linked ticket. When executed no trace is displayed and the exception is caught

remove try: except: blocks that log and raise exceptions

---

.github/workflows/build.yml
docs/explanations/access_control.md
docs/tutorials/python/sharing_settings.md
synapseclient/core/models/permission.py
synapseclient/core/transfer_bar.py
synapseclient/models/folder.py
synapseclient/models/mixins/access_control.py
synapseclient/models/mixins/storable_container.py
synapseclient/models/project.py
synapseclient/models/protocols/access_control_protocol.py
tests/integration/synapseclient/models/async/test_permissions_async.py
tests/integration/synapseclient/models/synchronous/test_permissions.py
tests/unit/synapseclient/models/async/unit_test_permissions_async.py
tests/unit/synapseclient/models/unit_test_permissions.py

- When executing the listing or deletion of ACLs the current process could hang for quite a while and not report anything back. This is due to how `asyncio.gather` was being used and no progress bar was actually being incremented.
- Support a progress bar that will report back as we are moving along the listing or deletion process. This is especially useful on projects with a large number of entities.
- I manually tested the progress bar on a project with 100 entities, and another with 1000 entities
- Existing integration tests should cover the validation of the business logic as nothing should have been affected, only the display of the progress bar in the console.
Screenshots!
Progress bar while listing acl:
Progress bar and results from a dry run of ACL deletion:
Progress bar during a …

[SYNPY-1604] ACL list/deletion progress bar

---

.github/scripts/delete_evaluations.py
.github/scripts/delete_projects.py
.github/scripts/delete_teams.py
.github/scripts/empty_trash.py
.github/workflows/test-cleanup.yml

- When integration tests run a failure in another OS or python version causes all test runs to quit out. This can cause resources to continue existing in Synapse and not be cleaned up.
- Create some simple test scripts to clean up the resources and run on a weekly cadence to clean up the resources
- This Github run was used to verify that the scripts could be run within github: https://github.com/Sage-Bionetworks/synapsePythonClient/actions/runs/15886384891/job/44799278492

[SYNPY-1618] Clean up test resources in Synapse created during integration test runs

---

synapseclient/models/table_components.py
tests/integration/synapseclient/models/async/test_table_async.py
tests/integration/synapseclient/models/synchronous/test_table.py

- When defining a ColumnType, or a FacetType you must use the Enum to set these values. This is problematic with the R-client where it won't be possible to create python style classes.
- Allow ColumnType and FacetType to be defined from strings, expanding usability
- Added integration testing around ColumnType
- I verified that I could install this python branch and hit this logic from R

[SYNPY-1607] Enum conversion from String

---

docs/reference/experimental/async/team.md
docs/reference/experimental/sync/team.md
docs/reference/rest_apis.md
synapseclient/api/__init__.py
synapseclient/api/api_client.py
synapseclient/api/team_services.py
synapseclient/api/user_services.py
synapseclient/client.py
synapseclient/models/__init__.py
synapseclient/models/protocols/team_protocol.py
synapseclient/models/team.py
synapseclient/models/user.py
synapseclient/team.py
tests/integration/synapseclient/models/async/test_team_async.py
tests/integration/synapseclient/models/synchronous/test_team.py
tests/unit/synapseclient/models/async/unit_test_team_async.py
tests/unit/synapseclient/models/async/unit_test_user_async.py
tests/unit/synapseclient/models/synchronous/unit_test_team.py
tests/unit/synapseclient/models/synchronous/unit_test_user.py

- Team and user method in the Synapse core class have been replaced and need to be deprecated
- A handful of new async methods still used the core Synapse class for it's implementation.
- Added asynchronous methods for retrieving user profiles by ID and username.
- Implemented a method to check if a user is certified.
- Deprecated several synchronous methods in the Synapse class, providing migration paths to new asynchronous methods in the UserProfile model.
- Updated the Team model to use new asynchronous API functions for team management (create, delete, get members, invite).
- Use UserGroupHeader to manage user group metadata.
- Enhanced documentation with migration examples for deprecated methods.
- Updated tests to reflect changes in error message formatting for non-existent teams.
- …

[SYNPY-1426] Deprecate user and team services in Synapse client

---

mkdocs.yml

- It is not clear how to get to our service desk/contact us from the documentation site
- Add a Contact us button that links to https://sagebionetworks.jira.com/servicedesk/customer/portal/9/group/16/create/206  
- I deployed the mkdocs site locally and verified that the link shows and goes to the destination as expected

[SYNPY-1637] Add 'Contact Us' section with support link in navigation

---

Pipfile

Patch: https://github.com/Sage-Bionetworks/synapsePythonClient/pull/1231
Remove `paramiko = "<4.0.0"` in Pipfile.

fix: remove unnecessary line in pipfile

---

tests/integration/synapseclient/models/async/test_agent_async.py
tests/integration/synapseclient/models/synchronous/test_agent.py

`Agent` Integration tests were not enabled because of a permission issue. 
Enable the integration tests done in this PR: https://github.com/Sage-Bionetworks/synapsePythonClient/pull/1152

[SYNPY-1588] Enable `Agent` Integration tests

---

docs/reference/experimental/async/team.md
docs/reference/experimental/sync/team.md
synapseclient/client.py
synapseclient/models/__init__.py
synapseclient/models/protocols/team_protocol.py
synapseclient/models/team.py
tests/integration/synapseclient/models/async/test_team_async.py
tests/integration/synapseclient/models/synchronous/test_team.py
tests/unit/synapseclient/models/synchronous/unit_test_team.py

This method here needs to be deprecated: [synapsePythonClient/synapseclient/client.py at 02d3b38d2a0f043811637064f61ae8b537e4253b · Sage-Bionetworks/synapsePythonClient](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/02d3b38d2a0f043811637064f61ae8b537e4253b/synapseclient/client.py#L5519-L5535)
Added a new method called `get_user_membership_status` under team
- Ensured that the example in the docstring works
- Surfaced the new function in documentation 
- Added test

[SYNPY-1633] Add membership_status to Team model and Deprecate Old Method

---

.pre-commit-config.yaml

Got an error in GH action run: 
```
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repog43qjmdu/py_env-python3/bin/bandit", line 3, in <module>
from bandit.cli.main import main
File "/home/runner/.cache/pre-commit/repog43qjmdu/py_env-python3/lib/python3.13/site-packages/bandit/__init__.py", line 5, in <module>
import pbr.version
ModuleNotFoundError: No module named 'pbr'
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repog43qjmdu/py_env-python3/bin/bandit", line 3, in <module>
from bandit.cli.main import main
File "/home/runner/.cache/pre-commit/repog43qjmdu/py_env-python3/lib/python3.13/site-packages/bandit/__init__.py", line 5, in <module>
import pbr.version
ModuleNotFoundError: No module named 'pbr'
Traceback (most recent call last): …
```

fix: update bandit to 1.8.0

---

.github/workflows/build.yml

- This action is deprecated
- Move to the latest non-deprecated version of the drop in replacement action
- Will review the run of this branch

Tech Debt: update SonarCloud action to use sonarqube-scan-action@v5.3.1

---

synapseclient/core/remote_file_storage_wrappers.py

- When uploading to an IBM based object storage bucket you would get the following error:
```
boto3.exceptions.S3UploadFailedError: Failed to upload /home/ec2-user/temp/test_file.txt to synpy-1198-ibm-bucket-testing/48b69ddc-9f28-4063-9f93-8efa7f262a15/test_file.txt: An error occurred (InvalidRequest) when calling the PutObject operation: Invalid canned ACL
```
- The error is received because IBM does not support more granular permissions and uses a different permissions schema that S3 uses as described in: https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
- First try to upload the object with the additional setting - and if it fails due to the canned acl error, upload it without the setting
- This solution is ok because the default behavior for IBM based …

[SYNPY-1198] Handle S3 upload errors by retrying without ACL for IBM buckets
