Sage-Bionetworks/synapsePythonClient

- synapseclient/client.py
- synapseclient/wiki.py
Sorry for all the auto formatting. My editor hates whitespaces ;-)
> Adding method to query wiki attachments

- synapseclient/__init__.py
- synapseclient/__main__.py
- synapseclient/activity.py
- synapseclient/cache.py
- synapseclient/client.py
- synapseclient/table.py
- synapseclient/team.py
- tests/integration/__init__.py
- tests/integration/integration_test.py
- tests/integration/test_command_line_client.py
- tests/integration/test_tables.py
- tests/integration/test_wikis.py
- tests/unit/unit_test_Cache.py
- tests/unit/unit_test_client.py
fixed caching bugs SYNPY-260 and SYNPY-259
> added wiki and team functions to client, fixed caching bugs

- synapseclient/__init__.py
- synapseclient/__main__.py
- synapseclient/client.py
- synapseclient/entity.py
- synapseclient/evaluation.py
- synapseclient/team.py
- synapseclient/utils.py
- tests/integration/test_command_line_client.py
- tests/integration/test_evaluations.py
- tests/integration/test_tables.py
- tests/unit/unit_test_client.py
> Team submission

- synapseclient/client.py
- synapseclient/retry.py
- synapseclient/wiki.py
fix docs for updating a wiki (SYNPY-192)
apply retry in _downloadFile when requesting S3 URL (SYNPY-290)
port random backoff back to develop branch (SYNPY-291)
> Fixes for retry and update wiki docs

- synapseclient/client.py
- synapseclient/team.py
- synapseclient/utils.py
- tests/integration/test_evaluations.py
- tests/integration/test_tables.py
SYNPY-221 Support new services for team submission
SYNPY-299 Bulk download of table associated file handles
> Download table column and team features

- synapseclient/__main__.py
- synapseclient/client.py
- tests/integration/integration_test_Entity.py
- tests/integration/test_command_line_client.py
SYNPY-64 Extract targetId from Links and follow.
> Add Link Class

- synapseclient/cache.py
- synapseclient/client.py
- synapseclient/entity.py
- synapseclient/utils.py
- tests/integration/test_evaluations.py
- tests/unit/unit_test_Cache.py
- tests/unit/unit_test_Entity.py
SYNPY-264, SYNPY-300, SYNPY-329, and SYNPY-130
> Bug fixes - unicode and handle missing content-length header

- README.md
- synapseclient/__main__.py
- synapseclient/cache.py
- synapseclient/client.py
- synapseclient/multipart_upload.py
- synapseclient/utils.py
- tests/integration/integration_test_Entity.py
- tests/integration/test_sftp_upload.py
- tests/unit/unit_test_multipart_upload.py
- tests/unit/unit_tests.py
SYNPY-330 syn.get with downloadLocation
deleting files from cache
tweaks to single-threaded multipart upload
> SYNPY-330 syn.get with downloadLocation

- synapseclient/__main__.py
- synapseclient/client.py
- synapseclient/dict_object.py
- synapseclient/multipart_upload.py
- synapseclient/table.py
- tests/integration/test_multipart_upload.py
- tests/unit/unit_test_lock.py
- tests/unit/unit_tests.py
Fixes for windows bugs and get test_randomly_failing_parts to pass consistently
> pre-release bug fixes

- synapseclient/client.py
> Fix typo in login docstring

- synapseclient/__main__.py
- synapseclient/client.py
- synapseclient/multipart_upload.py
- synapseclient/table.py
- synapseclient/utils.py
- tests/unit/unit_test_multipart_upload.py
fix for SYNPY-372 integer argument expected, got float in large file upload
> fix for SYNPY-372 integer argument expected

- README.md
Change links to use docs.synapse.org
> Update readme with links to new docs

- synapseclient/client.py
- synapseclient/exceptions.py
- synapseclient/retry.py
- synapseclient/utils.py
- tests/integration/integration_test.py
- tests/integration/test_download.py
- tests/unit/unit_test_download.py
- tests/unit/unit_tests.py
SYNPY-309 resume partial downloads using range header
SYNPY-388 fix sporadic test failures related to team creation
> resume partial downloads

- synapseclient/client.py
> Make ftp download py3 compatible.

- synapseclient/__init__.py
- synapseclient/__main__.py
- synapseclient/client.py
Regarding issue 229 for synapseDocs (https://github.com/Sage-Bionetworks/synapseDocs/issues/229)
> updated links to point to the new doc site

- synapseutils/copy.py
Wiki filehandles are stored in wiki.attachmentFileHandle.
> Update attachment for filehandles

- synapseclient/cache.py
- synapseclient/client.py
- synapseclient/entity.py
- synapseutils/copy.py
- tests/integration/integration_test.py
- tests/integration/integration_test_Entity.py
- tests/integration/test_sftp_upload.py
- tests/integration/test_synapseutils.py
- tests/unit/unit_test_client.py
Needed to merge both issue branches together for tests to pass.
> SYNPY-438 and SYNPY-443 to master branch

- tests/integration/test_query.py
> reverted changes to test. now the only change is having time.sleep() … (SYNPY-426)

- synapseclient/client.py
- synapseclient/entity.py
- synapseutils/copy.py
- synapseutils/walk.py
- tests/integration/integration_test.py
- tests/integration/test_evaluations.py
- tests/unit/unit_test_Entity.py
- tests/unit/unit_test_client.py
Add helper function to get children of containers.
> Remove chunkedQuery dependency and added getChildren() (SYNPY-435)

- synapseclient/client.py
Already had this in the develop branch:
https://github.com/Sage-Bionetworks/synapsePythonClient/pull/435
but had to cherry the commits because there were other commits included when i tried to make a pull request from my SYNPY-504 branch into master
> Synpy 504 merge to master

- synapseclient/client.py
- synapseclient/dozer.py
- synapseclient/lock.py
- synapseclient/retry.py
- tests/unit/unit_test_doze.py
This change was reviewed under PR against 'develop': https://github.com/Sage-Bionetworks/synapsePythonClient/pull/464
The current PR is introduced simply to merge into 'master'
> SYNR-1125-II

- synapseclient/client.py
already pulled into develop. cherry picking into master branch
> Synpy-511 cherry-pick to master

- synapseclient/table.py
- tests/unit/unit_test_tables.py
Already been merged to develop.
> SYNPY-304 to master

- release_notes/release-1.7.md
- synapseclient/__init__.py
- synapseclient/client.py
- synapseclient/concrete_types.py
- synapseclient/lock.py
- synapseclient/logging_setup.py
- synapseclient/multipart_upload.py
- synapseclient/retry.py
- synapseclient/synapsePythonClient
- synapseclient/table.py
- synapseclient/upload_functions.py
- synapseclient/utils.py
- tests/integration/__init__.py
- tests/integration/integration_test_Entity.py
- tests/integration/test_command_line_client.py
- tests/integration/test_tables.py
- tests/unit/unit_test_tables.py
> Manual merge of master into develop + test fixes after merge (SYNPY-613)

- synapseclient/table.py
- tests/unit/unit_test_tables.py
Add link to column types to add
> table.cast_valuies() now handles columnType=='LINK'

- .dockerignore
- Dockerfile
This will now install the appropriate branch/tag/etc when built locally or in Dockerhub.
Fixes https://sagebionetworks.jira.com/browse/SYNPY-943
> SYNPY-943 update the dockerfile to use current github code

- synapseclient/annotations.py
- synapseclient/client.py
- synapseclient/core/exceptions.py
- synapseclient/core/retry.py
- synapseclient/core/utils.py
- synapseclient/entity.py
- synapseclient/table.py
- tests/integration/synapseclient/integration_test.py
- tests/integration/synapseclient/integration_test_Entity.py
- tests/unit/synapseclient/core/unit_test_retry.py
- tests/unit/synapseclient/unit_tests.py
un-private functions that is used outside of the module that contains it
> SYNPY-859 organize internal interface

- docs/build/html/index.html
> Removed circular link in spc overview

- synapseclient/__main__.py
- tests/integration/test_command_line_client.py
Command line tool to create table from csv
> Synpy 735 command line - create table

- setup.py
Modify setup.py to allow installation into a Python 3.8 environment.
All tests passed.
Fixes #719.
> Add support for Python 3.8 (SYNPY-1034)

- synapseclient/client.py
- synapseclient/core/utils.py
- synapseclient/producer_consumer_download_threads.py
For initial meeting with @zimingd at 3 PM today, tests are actively being developed locally and PR will be updated ASAP.
> Initial multithreaded download in current client, no tests

- synapseclient/core/utils.py
- tests/unit/synapseclient/core/unit_test_utils.py
Collectively written during Code Review session 5/29
https://github.com/Sage-Bionetworks/synapsePythonClient/issues/747
> Unit test for humanizeBytes

- docs/news.rst
- synapseclient/table.py
> py-2.1.1 release notes

- .github/workflows/build.yml
I missed this step in the Travis->GH Actions conversion
> Add flake8 to GitHub Actions test workflow

- synapseclient/evaluation.py
Make `id` and `etag` required fields in the `SubmissionStatus` object as these fields are required for creating `Annotation` object.
> Add id and etag in __init__ for SubmissionStatus object

- synapseclient/core/remote_file_storage_wrappers.py
Retry on e.g. the below error which can result from an SFTP server that is congested or intentionally throttling to prevent brute force attacks. This can happen in the course of integration tests if there are multiple concurrent runs of the tests.
https://stackoverflow.com/a/29225295
```
ERROR    paramiko.transport:transport.py:1817     raise SSHException(
ERROR    paramiko.transport:transport.py:1817 paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR    paramiko.transport:transport.py:1817
=========================== short test summary info ============================
FAILED tests/integration/synapseclient/core/upload/test_sftp_upload.py::test_synGet_sftpIntegration
============= 1 failed, 94 passed, 2 skipped in 600.00s (0:10:00) ==============
Error: Process …
```
> retry on pysftp banner read error

- synapseclient/client.py
- tests/unit/synapseclient/unit_test_client.py
https://sagebionetworks.jira.com/browse/SYNPY-885
this PR allows user to customized the cahe root directory, or keep it as the default directory same as core.Cache
> SYNPY-885 cache root dir

- docs/Credentials.rst
- synapseclient/.synapseConfig
Doc updates for https://github.com/Sage-Bionetworks/synapsePythonClient/pull/804
> SYNPY-1058 auth token doc

- docs/S3Storage.rst
- synapseclient/client.py
Incorporate some suggested feedback
> Storage migration doc updates

- synapseclient/client.py
- tests/unit/synapseclient/unit_test_client.py
adding to client instead of `challengeutils`: https://github.com/Sage-Bionetworks/challengeutils/pull/204.
@jkiang13 , this is ready for review - Thanks!
> SYNPY-1111-Add function to get certification status

- synapseclient/annotations.py
- synapseclient/client.py
- tests/unit/synapseclient/unit_test_annotations.py
- tests/unit/synapseclient/unit_test_client.py
Change
- add compare helper function for comparing the bundle annotation and new annotation
- add unit tests for modification in client.py and annotations.py
> Synpy 829 store update annotations

- synapseclient/annotations.py
- tests/integration/synapseclient/integration_test.py
- tests/unit/synapseclient/unit_test_annotations.py
Support booleans in entity annotations
> SYNPY-1129 boolean annotations

- .github/workflows/build.yml
Build wheels in addition to the source distributions when packaging synapseclient.
> SYNPY-1120 build wheel

- synapseclient/core/cache.py
And I have to read the code to remember ;)
> I always forget what the cache date format is

- tests/integration/synapseclient/integration_test.py
- tests/integration/synapseclient/test_evaluations.py
Cleans up some evaluation integration tests, in particular one that had become unstable related to: https://sagebionetworks.jira.com/browse/PLFM-6686
> Fix for evaluation submission tests

- synapseclient/core/upload/multipart_upload.py
- synapseclient/table.py
- synapseutils/migrate_functions.py
- tests/unit/synapseclient/core/upload/unit_test_multipart_upload.py
- tests/unit/synapseclient/unit_test_tables.py
- tests/unit/synapseutils/unit_test_synapseutils_migrate.py
Addresses the following issues, one per commit:
[SYNPY-1123](https://sagebionetworks.jira.com/browse/SYNPY-1123)
[SYNPY-1130](https://sagebionetworks.jira.com/browse/SYNPY-1130) 
[SYNPY-1134](https://sagebionetworks.jira.com/browse/SYNPY-1134)
[SYNPY-1135](https://sagebionetworks.jira.com/browse/SYNPY-1135)
[SYNPY-1136](https://sagebionetworks.jira.com/browse/SYNPY-1136)
> SYNPY-1137 migration fixes

- docs/news.rst
Documentation for patch release 2.3.1.
This is minor release to get boolean annotation support out.
Preview:
https://jkiang13.github.io/synapsePythonClient/build/html/news.html#xx
> v2.3.1 doc

- synapseclient/client.py
https://github.com/Sage-Bionetworks/synapser/pull/297
> SYNR-1474 doc typo

- synapseclient/__main__.py
- tests/unit/synapseclient/unit_test_commandline.py
change
- add command exit code 1 when command execute failed
> Synpy 948 set annotations proper error code

- synapseclient/table.py
- tests/unit/synapseclient/unit_test_tables.py
Change
- fix the issue that asDataFrame function reformate the boolean-like string column to Boolean value by pandas
- add unit test to verify the issue no longer exist
> SYNPY-1150-boolean_string_column_reformatted

- synapseclient/__main__.py
- tests/unit/synapseclient/unit_test_commandline.py
Change
- check the args with file or FILE before handling the store command
- add unit test for test case
> SYNPY-1113-store_command_positional_arg_file

- docs/Credentials.rst
- docs/news.rst
- synapseclient/synapsePythonClient
Preview here:
https://jkiang13.github.io/synapsePythonClient/build/html/news.html#id1
> py-2.4 release notes

- synapseclient/table.py
- tests/unit/synapseclient/unit_test_tables.py
Change
- fix the issue that pandas infer the data type of coulmn
- add unit test to verify column type are match with Synapse table
> Synpy 1146 writing boolean from df into synapse table

- synapseutils/sync.py
There was a bug with #873 which caused integration tests to fail.  This is the fix
> [SYNPY-1163] Fix integration test

- docs/build/html/news.html
- docs/news.rst
- synapseclient/client.py
- synapseclient/evaluation.py
View JIra ticket for more details.  @jkiang13 - this is ready to be reviewed.
> [SYNPY-1093] Add urlparse to ensure rest call can be called

- .github/workflows/build.yml
- synapseclient/table.py
- tests/integration/synapseclient/test_tables.py
Change
- if the column type is DATE, change the date format to unix epoch and trailing the 3 digit of millisecond
> [SYNPY-1156] dateTime_dataframe_store_to_Synapse

- synapseclient/__main__.py
Reverts Sage-Bionetworks/synapsePythonClient#693
Going to phase this out slowly so we don't create a major release.
> Revert "[SYNPY-737] Remove non-standard single hyphen long arguments"

- tests/integration/synapseclient/test_command_line_client.py
Reverts Sage-Bionetworks/synapsePythonClient#880
> Revert "[SYNPY-737] Fix integration tests"

- docs/Views.rst
- docs/reticulate.rst
This PR replaces `add_default_columns` with the correct parameter `addDefaultViewColumns` in EntityViewSchema function.
> [SYNPY-997] Fix typo in Views documentation

- synapseclient/table.py
Use `test_pandas_import` function.
> [SYNPY-728] improve no pandas error

- synapseclient/__init__.py
- synapseclient/client.py
- synapseclient/entity.py
- synapseclient/table.py
- tests/integration/synapseclient/test_tables.py
- tests/unit/synapseclient/unit_test_tables.py
This PR will add initial support for the new Datasets entity (mentioned by this [JIRA ticket](https://sagebionetworks.jira.com/browse/SYNPY-1207)), including methods such as:
- adding a single DatasetItem
- adding a list of DatasetItems
- removing a single DatasetItem
- ~~adding a Synapse Folder to the Dataset~~
- ~~adding a list of Synapse Folders to the Dataset~~
> [SYNPY-1207] Add Dataset support

- .github/workflows/codeql-analysis.yml
> [SYNPY-1235] Create codeql-analysis.yml

- synapseclient/client.py
- tests/integration/synapseclient/test_tables.py
Added ability to add default annotation columns, so need to set those parameters to False so that the tests pass.
> Fix dataset tests

- synapseclient/client.py
- tests/unit/synapseclient/unit_test_client.py
This message appears to be out of date. I've updated it to reflect the current SWC ui.
> [SYNPY-1224] Correct SynapseUnmetAccessRestrictions message

- synapseclient/client.py
- tests/unit/synapseclient/unit_test_client.py
activity parameter expects Activity class, so fast fail if it is not.
> [SYNPY-1031] check activity

- synapseutils/sync.py
- tests/integration/synapseutils/test_synapseutils_sync.py
* Update sync docs
* Strip the values of white spaces when splitting by ;
> [SYNPY-1053, SYNPY-566, SYNPY-1234] Update sync docs & Strip the values of white spaces when splitting by `;`

- synapseclient/__main__.py
- synapseclient/client.py
Document the deprecation of passwords/APIs to push only using PAT
> Document Deprecating support for passwords to push towards PAT

- synapseclient/table.py
- tests/unit/synapseclient/unit_test_tables.py
Fixes #940 
@linglp can you test this by installing my branch locally with schematic?
> [SYNPY-1237] Add mixed-integer-float data type

- .github/workflows/build.yml
- README.md
- setup.py
> [SYNPY-1246] Add  Python 3.11 support

- synapseclient/__main__.py
- tests/integration/synapseclient/test_command_line_client.py
This is for a major release 3.0
> [SYNPY-737] Remove non-standard single dash long cli parameters

- setup.py
- synapseclient/table.py
- synapseutils/sync.py
- tests/unit/synapseutils/unit_test_synapseutils_sync.py
caused by https://github.com/urllib3/urllib3/pull/2705/files
Fixes #957 
This might need more discussion as locking down this version _could_ cause be problematic for users using python 3.10+.
> Lock down urllib3

- .github/workflows/build.yml
- synapseclient/core/constants/concrete_types.py
- synapseclient/core/upload/upload_functions.py
- tests/unit/synapseclient/unit_test_client.py
Allow for files to upload into external GCP bucket
> [SYNPY-1266] Add support for GCP bucket

- synapseclient/evaluation.py
* Simplify `super()` calls
* Use f-string interpolation
* Add type hints
> [SYNPY-622] Improve evaluation.py syntax

- setup.cfg
- setup.py
Clean up setup.py by using setup.cfg and pyproject.toml
> Clean up setup.py by using setup.cfg

- synapseclient/client.py
- synapseclient/core/utils.py
- tests/unit/synapseclient/core/unit_test_utils.py
- tests/unit/synapseclient/unit_test_client.py
This include the changes from: https://github.com/Sage-Bionetworks/synapsePythonClient/pull/976#issue-1777828258
I did not have permissions on the fork to resolve the merge conflicts so i am moving it over here
> [SYNPY-967] deprecated memoize and added @lru_cache

- CONTRIBUTING.md
- synapseclient/client.py
This PR adds type hints to several functions in `client.py` (I did more than 5 because most of them only have one or two variables).
I also added a quick note to CONTRIBUTING.md because I had an issue getting the `pipenv install` to work due to my having an out of date pipenv version.
> [SYNPY-1282] Adds Type Hinting to `client.py`

- Pipfile.lock
- setup.cfg
Background:
https://github.com/Sage-Bionetworks/synapsePythonClient/security/dependabot/7
Updating dependency a few patch version to push us out of the affected version range
> [SYNPY-1293] Update urllib3 version dependency

- CONTRIBUTING.md
- README.md
Moving some content around in the contributing file to let it flow a bit better for someone jumping into the project
> [SYNPY-1299] Clean up contributing.md

- CONTRIBUTING.md
Update contributing.md to point to service desk
> [SYNPY-1299] Update contributing.md to point to service desk

- Dockerfile
**Problem:**
Newer dependencies are not correctly installed when you run `docker build .` with the current Dockerfile.
**Solution:**
Update the Dockerfile to correctly install the dependencies.
> Updates Dockerfile to Correctly Install Dependencies

- CONTRIBUTING.md
**Problem:**
In the contributing.md guide we were blanket mentioning to fork the repo and work from there.
**Solution:**
I updated the docs to mention the flow for internal/external folks contributing to the repo
> Update notes for getting started for internal folks

- synapseclient/evaluation.py
- synapseutils/sync.py
Problem:
Formatting on 2 pieces was broken
Solution:
Correct formatting
Testing:
Viewed on docs site
> [SYNPY-1370] Minor formatting fixes

- README.md
- synapseclient/client.py
- synapseclient/core/credentials/cred_data.py
- tests/integration/synapseclient/integration_test.py
**Problem:**
1. Functions that have been deprecated since 2.1.0 still exist
2. Some documentation needed updating
**Solution:**
Removing deprecated functions
**Testing:**
Integration/unit tests
> [SYNPY-1392] Remove some deprecated pieces

- docs/explanations/structuring_your_project.md
Problem:
The original document is mainly targeting Data Curator App users. places:
Solution:
1. Tweak the content and add examples to make it project agnostic.
2. Fixed formatting issues
Testing:
N/A
> [SYNPY-1387] Update Structure Project doc

- synapseclient/models/file.py
Problem:
1. The store docstring didn't go a great job at explaining what you can do with it
Solution:
1. Going over some use cases with the store method
Testing:
N/A
> [SYNPY-1416] Adding to the file.store docstring

- synapseutils/walk_functions.py
We created a sequence diagram of the walk function during the scidevs meeting. This is to publish that result.
**This depends on changes from https://github.com/Sage-Bionetworks/synapsePythonClient/pull/1061 - 1061 should be merged first.**
**Testing:**
> [SYNPY-1415] Publish sequence diagram for walk function

- Pipfile.lock
- setup.cfg
- synapseclient/client.py
- synapseclient/core/upload/multipart_upload_async.py
- synapseclient/core/upload/upload_functions_async.py
- synapseclient/core/utils.py
**Problem:**
1. loky crash when used from a uwsgi process: https://github.com/joblib/loky/issues/207
**Solution:**
1. Removing the use of multi-processing from the client
**Testing:**
1. Lingling was able to verify that the changes are working as expected
2. Integration tests are still all passing here
> [SYNPY-1494] Remove process pool executor

- Pipfile.lock
- setup.cfg
- synapseclient/table.py
- tests/integration/synapseclient/core/test_external_storage.py
- tests/unit/synapseclient/unit_test_tables.py
**Problem:**
We do not currently support passing `keep_default_na` and `na_values` to `CSVFileTable.asDataFrame` so we are only offering the default functionality of `pandas.read_csv` to users. For example, if someone wanted to have the string `"None"` from a Synapse table remain a string and not become `NA` when exported to a CSV file, they would be unable to.
**Solution:**
Add `**kwargs` as arguments to `CSVFileTable.asDataFrame` and pass them down to `pandas.read_csv` through `_csv_to_pandas_df`.
**Testing:**
I added unit tests for this new functionality and tested my changes with the following script:
```
from synapseclient.table import CsvFileTable
syn = synapseclient.Synapse()
syn.login()
import pandas as pd
data = {
'id': ['abc', '', 'None', None, 'NA'], …
```
> [SYNPY-1509] Updates `NA` handling for `CSVFileTable.asDataFrame`

- Pipfile.lock
- setup.cfg
- synapseclient/client.py
- synapseclient/core/dozer.py
**Changes:**
1. Reduce retry delay in-between table queries.
2. Update versioning for OTEL components to prevent issues with version ranges being used within schematic.
3. Wrap endpoint querying with retry logic.
4. Adding some trace collection around dozing/waiting for async results from synapse.
> [FDS-2373] Update retry delay, add some otel traces, add retry to url creation

- synapseclient/client.py
- synapseclient/models/mixins/access_control.py
- synapseclient/models/protocols/access_control_protocol.py
**Problem:**
1. The docstring for this function is not clear what the 2 given parameters do
**Solution:**
1. Add a more verbose docstring around these 2 function parameters
> Update the docstring for setPermissions to be clearer

- docs/tutorials/python/tutorial_scripts/dataset.py
During validation we noticed this typo, so we should fix it.
Fix the typo.
N/A
> Updates dataset tutorial to fix typo
